/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  SearchParams,
  SearchQueryResponseDto
} from '../../model';

import { customFetch } from '../../../lib/api/customFetch.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type download1Response200 = {
  data: Blob
  status: 200
}

export type download1ResponseSuccess = (download1Response200) & {
  headers: Headers;
};
;

export type download1Response = (download1ResponseSuccess)

export const getDownload1Url = (versionId: string,) => {




  return `/api/v1/evidences/${versionId}/download`
}

/**
 * Valida el acceso por rol y carrera antes de retornar los bytes del archivo.
 * @summary Descargar un archivo de evidencia
 */
export const download1 = async (versionId: string, options?: Parameters<typeof customFetch>[1]): Promise<download1Response> => {

  return customFetch<download1Response>(getDownload1Url(versionId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getDownload1QueryKey = (versionId: string,) => {
    return [
    `/api/v1/evidences/${versionId}/download`
    ] as const;
    }


export const getDownload1QueryOptions = <TData = Awaited<ReturnType<typeof download1>>, TError = unknown>(versionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof download1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownload1QueryKey(versionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof download1>>> = ({ signal }) => download1(versionId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: versionId !== null && versionId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof download1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type Download1QueryResult = NonNullable<Awaited<ReturnType<typeof download1>>>
export type Download1QueryError = unknown


export function useDownload1<TData = Awaited<ReturnType<typeof download1>>, TError = unknown>(
 versionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof download1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof download1>>,
          TError,
          Awaited<ReturnType<typeof download1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownload1<TData = Awaited<ReturnType<typeof download1>>, TError = unknown>(
 versionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof download1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof download1>>,
          TError,
          Awaited<ReturnType<typeof download1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownload1<TData = Awaited<ReturnType<typeof download1>>, TError = unknown>(
 versionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof download1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Descargar un archivo de evidencia
 */

export function useDownload1<TData = Awaited<ReturnType<typeof download1>>, TError = unknown>(
 versionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof download1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownload1QueryOptions(versionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type searchResponse200 = {
  data: SearchQueryResponseDto
  status: 200
}

export type searchResponseSuccess = (searchResponse200) & {
  headers: Headers;
};
;

export type searchResponse = (searchResponseSuccess)

export const getSearchUrl = (params?: SearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/evidences/search?${stringifiedParams}` : `/api/v1/evidences/search`
}

/**
 * Enruta la búsqueda por sinónimos usando LLM y aplica aislamiento de carrera.
 * @summary Buscar evidencias con IA o búsqueda tradicional
 */
export const search = async (params?: SearchParams, options?: Parameters<typeof customFetch>[1]): Promise<searchResponse> => {

  return customFetch<searchResponse>(getSearchUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getSearchQueryKey = (params?: SearchParams,) => {
    return [
    `/api/v1/evidences/search`, ...(params ? [params] : [])
    ] as const;
    }


export const getSearchQueryOptions = <TData = Awaited<ReturnType<typeof search>>, TError = unknown>(params?: SearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof search>>> = ({ signal }) => search(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchQueryResult = NonNullable<Awaited<ReturnType<typeof search>>>
export type SearchQueryError = unknown


export function useSearch<TData = Awaited<ReturnType<typeof search>>, TError = unknown>(
 params: undefined |  SearchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof search>>,
          TError,
          Awaited<ReturnType<typeof search>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearch<TData = Awaited<ReturnType<typeof search>>, TError = unknown>(
 params?: SearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof search>>,
          TError,
          Awaited<ReturnType<typeof search>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearch<TData = Awaited<ReturnType<typeof search>>, TError = unknown>(
 params?: SearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Buscar evidencias con IA o búsqueda tradicional
 */

export function useSearch<TData = Awaited<ReturnType<typeof search>>, TError = unknown>(
 params?: SearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






