/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  IndicatorWorkflowResponseDto,
  RejectIndicatorRequestDto
} from '../../model';

import { customFetch } from '../../../lib/api/customFetch.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type rejectResponse200 = {
  data: IndicatorWorkflowResponseDto
  status: 200
}

export type rejectResponseSuccess = (rejectResponse200) & {
  headers: Headers;
};
;

export type rejectResponse = (rejectResponseSuccess)

export const getRejectUrl = (indicatorId: string,) => {




  return `/api/v1/indicators/${indicatorId}/reject`
}

/**
 * @summary Rechazar indicador (requiere evidencia cargada)
 */
export const reject = async (indicatorId: string,
    rejectIndicatorRequestDto: RejectIndicatorRequestDto, options?: Parameters<typeof customFetch>[1]): Promise<rejectResponse> => {

  return customFetch<rejectResponse>(getRejectUrl(indicatorId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(rejectIndicatorRequestDto)
  }
);}





export const getRejectMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reject>>, TError,{indicatorId: string;data: RejectIndicatorRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof reject>>, TError,{indicatorId: string;data: RejectIndicatorRequestDto}, TContext> => {

const mutationKey = ['reject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reject>>, {indicatorId: string;data: RejectIndicatorRequestDto}> = (props) => {
          const {indicatorId,data} = props ?? {};

          return  reject(indicatorId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RejectMutationResult = NonNullable<Awaited<ReturnType<typeof reject>>>
    export type RejectMutationBody = RejectIndicatorRequestDto
    export type RejectMutationError = unknown

    /**
 * @summary Rechazar indicador (requiere evidencia cargada)
 */
export const useReject = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reject>>, TError,{indicatorId: string;data: RejectIndicatorRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reject>>,
        TError,
        {indicatorId: string;data: RejectIndicatorRequestDto},
        TContext
      > => {
      return useMutation(getRejectMutationOptions(options), queryClient);
    }
    export type approveResponse200 = {
  data: IndicatorWorkflowResponseDto
  status: 200
}

export type approveResponseSuccess = (approveResponse200) & {
  headers: Headers;
};
;

export type approveResponse = (approveResponseSuccess)

export const getApproveUrl = (indicatorId: string,) => {




  return `/api/v1/indicators/${indicatorId}/approve`
}

/**
 * @summary Aprobar indicador (requiere evidencia cargada)
 */
export const approve = async (indicatorId: string, options?: Parameters<typeof customFetch>[1]): Promise<approveResponse> => {

  return customFetch<approveResponse>(getApproveUrl(indicatorId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getApproveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approve>>, TError,{indicatorId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof approve>>, TError,{indicatorId: string}, TContext> => {

const mutationKey = ['approve'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof approve>>, {indicatorId: string}> = (props) => {
          const {indicatorId} = props ?? {};

          return  approve(indicatorId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ApproveMutationResult = NonNullable<Awaited<ReturnType<typeof approve>>>

    export type ApproveMutationError = unknown

    /**
 * @summary Aprobar indicador (requiere evidencia cargada)
 */
export const useApprove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approve>>, TError,{indicatorId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof approve>>,
        TError,
        {indicatorId: string},
        TContext
      > => {
      return useMutation(getApproveMutationOptions(options), queryClient);
    }
