/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApproveResponseDto,
  PendingIndicatorResponseDto,
  RejectRequestDto,
  RejectResponseDto
} from '../../model';

import { customFetch } from '../../../lib/api/customFetch.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type rejectResponse200 = {
  data: RejectResponseDto
  status: 200
}

export type rejectResponseSuccess = (rejectResponse200) & {
  headers: Headers;
};
;

export type rejectResponse = (rejectResponseSuccess)

export const getRejectUrl = (indicatorId: string,) => {




  return `/api/v1/indicators/${indicatorId}/reject`
}

/**
 * Rol TD. Transiciona a OBSERVADO y crea observación.
 * @summary Rechazar indicador
 */
export const reject = async (indicatorId: string,
    rejectRequestDto: RejectRequestDto, options?: Parameters<typeof customFetch>[1]): Promise<rejectResponse> => {

  return customFetch<rejectResponse>(getRejectUrl(indicatorId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(rejectRequestDto)
  }
);}





export const getRejectMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reject>>, TError,{indicatorId: string;data: RejectRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof reject>>, TError,{indicatorId: string;data: RejectRequestDto}, TContext> => {

const mutationKey = ['reject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reject>>, {indicatorId: string;data: RejectRequestDto}> = (props) => {
          const {indicatorId,data} = props ?? {};

          return  reject(indicatorId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RejectMutationResult = NonNullable<Awaited<ReturnType<typeof reject>>>
    export type RejectMutationBody = RejectRequestDto
    export type RejectMutationError = unknown

    /**
 * @summary Rechazar indicador
 */
export const useReject = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reject>>, TError,{indicatorId: string;data: RejectRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reject>>,
        TError,
        {indicatorId: string;data: RejectRequestDto},
        TContext
      > => {
      return useMutation(getRejectMutationOptions(options), queryClient);
    }
    export type approveResponse200 = {
  data: ApproveResponseDto
  status: 200
}

export type approveResponseSuccess = (approveResponse200) & {
  headers: Headers;
};
;

export type approveResponse = (approveResponseSuccess)

export const getApproveUrl = (indicatorId: string,) => {




  return `/api/v1/indicators/${indicatorId}/approve`
}

/**
 * Rol TD. Transiciona a APROBADO y resuelve observaciones.
 * @summary Aprobar indicador
 */
export const approve = async (indicatorId: string, options?: Parameters<typeof customFetch>[1]): Promise<approveResponse> => {

  return customFetch<approveResponse>(getApproveUrl(indicatorId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getApproveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approve>>, TError,{indicatorId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof approve>>, TError,{indicatorId: string}, TContext> => {

const mutationKey = ['approve'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof approve>>, {indicatorId: string}> = (props) => {
          const {indicatorId} = props ?? {};

          return  approve(indicatorId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ApproveMutationResult = NonNullable<Awaited<ReturnType<typeof approve>>>

    export type ApproveMutationError = unknown

    /**
 * @summary Aprobar indicador
 */
export const useApprove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approve>>, TError,{indicatorId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof approve>>,
        TError,
        {indicatorId: string},
        TContext
      > => {
      return useMutation(getApproveMutationOptions(options), queryClient);
    }
    export type listPendingResponse200 = {
  data: PendingIndicatorResponseDto[]
  status: 200
}

export type listPendingResponseSuccess = (listPendingResponse200) & {
  headers: Headers;
};
;

export type listPendingResponse = (listPendingResponseSuccess)

export const getListPendingUrl = () => {




  return `/api/v1/indicators/pending`
}

/**
 * Rol TD. Retorna los indicadores en estado SUBIDO o SUBSANADO.
 * @summary Listar indicadores pendientes de revisión
 */
export const listPending = async ( options?: Parameters<typeof customFetch>[1]): Promise<listPendingResponse> => {

  return customFetch<listPendingResponse>(getListPendingUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPendingQueryKey = () => {
    return [
    `/api/v1/indicators/pending`
    ] as const;
    }


export const getListPendingQueryOptions = <TData = Awaited<ReturnType<typeof listPending>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPending>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPendingQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPending>>> = ({ signal }) => listPending({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPending>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPendingQueryResult = NonNullable<Awaited<ReturnType<typeof listPending>>>
export type ListPendingQueryError = unknown


export function useListPending<TData = Awaited<ReturnType<typeof listPending>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPending>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPending>>,
          TError,
          Awaited<ReturnType<typeof listPending>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPending<TData = Awaited<ReturnType<typeof listPending>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPending>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPending>>,
          TError,
          Awaited<ReturnType<typeof listPending>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPending<TData = Awaited<ReturnType<typeof listPending>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPending>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar indicadores pendientes de revisión
 */

export function useListPending<TData = Awaited<ReturnType<typeof listPending>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPending>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPendingQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






