/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  CreateProcessRequestDto,
  ProcessResponseDto
} from '../../model';

import { customFetch } from '../../../lib/api/customFetch';




export type createProcessResponse201 = {
  data: ProcessResponseDto
  status: 201
}

export type createProcessResponse400 = {
  data: void
  status: 400
}

export type createProcessResponse403 = {
  data: void
  status: 403
}

export type createProcessResponse404 = {
  data: void
  status: 404
}

export type createProcessResponse409 = {
  data: void
  status: 409
}

export type createProcessResponseSuccess = (createProcessResponse201) & {
  headers: Headers;
};
export type createProcessResponseError = (createProcessResponse400 | createProcessResponse403 | createProcessResponse404 | createProcessResponse409) & {
  headers: Headers;
};

export type createProcessResponse = (createProcessResponseSuccess | createProcessResponseError)

export const getCreateProcessUrl = () => {




  return `/api/v1/processes`
}

/**
 * Inicia un proceso clonando la taxonomía de una plantilla (Fase -> Subfase).
 * @summary Crear un nuevo proceso
 */
export const createProcess = async (createProcessRequestDto: CreateProcessRequestDto, options?: RequestInit): Promise<createProcessResponse> => {

  return customFetch<createProcessResponse>(getCreateProcessUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createProcessRequestDto)
  }
);}




export const getCreateProcessMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProcess>>, TError,{data: CreateProcessRequestDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createProcess>>, TError,{data: CreateProcessRequestDto}, TContext> => {

const mutationKey = ['createProcess'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProcess>>, {data: CreateProcessRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  createProcess(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateProcessMutationResult = NonNullable<Awaited<ReturnType<typeof createProcess>>>
    export type CreateProcessMutationBody = CreateProcessRequestDto
    export type CreateProcessMutationError = void

    /**
 * @summary Crear un nuevo proceso
 */
export const useCreateProcess = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProcess>>, TError,{data: CreateProcessRequestDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProcess>>,
        TError,
        {data: CreateProcessRequestDto},
        TContext
      > => {
      return useMutation(getCreateProcessMutationOptions(options), queryClient);
    }
