/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AssignResponsibleRequestDto,
  CreateProcessRequestDto,
  EligibleResponsibleDto,
  ProcessResponseDto,
  ProcessResponsibleDto,
  ProcessSummaryResponseDto
} from '../../model';

import { customFetch } from '../../../lib/api/customFetch.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type assignResponsibleResponse200 = {
  data: ProcessResponsibleDto
  status: 200
}

export type assignResponsibleResponse400 = {
  data: void
  status: 400
}

export type assignResponsibleResponse403 = {
  data: void
  status: 403
}

export type assignResponsibleResponse404 = {
  data: void
  status: 404
}

export type assignResponsibleResponse409 = {
  data: void
  status: 409
}

export type assignResponsibleResponseSuccess = (assignResponsibleResponse200) & {
  headers: Headers;
};
export type assignResponsibleResponseError = (assignResponsibleResponse400 | assignResponsibleResponse403 | assignResponsibleResponse404 | assignResponsibleResponse409) & {
  headers: Headers;
};

export type assignResponsibleResponse = (assignResponsibleResponseSuccess | assignResponsibleResponseError)

export const getAssignResponsibleUrl = (processId: string,) => {




  return `/api/v1/processes/${processId}/responsible`
}

/**
 * Designa un coordinador como responsable único del proceso ACTIVE.
 * @summary Asignar responsable [CC]
 */
export const assignResponsible = async (processId: string,
    assignResponsibleRequestDto: AssignResponsibleRequestDto, options?: Parameters<typeof customFetch>[1]): Promise<assignResponsibleResponse> => {

  return customFetch<assignResponsibleResponse>(getAssignResponsibleUrl(processId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(assignResponsibleRequestDto)
  }
);}





export const getAssignResponsibleMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignResponsible>>, TError,{processId: string;data: AssignResponsibleRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof assignResponsible>>, TError,{processId: string;data: AssignResponsibleRequestDto}, TContext> => {

const mutationKey = ['assignResponsible'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof assignResponsible>>, {processId: string;data: AssignResponsibleRequestDto}> = (props) => {
          const {processId,data} = props ?? {};

          return  assignResponsible(processId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AssignResponsibleMutationResult = NonNullable<Awaited<ReturnType<typeof assignResponsible>>>
    export type AssignResponsibleMutationBody = AssignResponsibleRequestDto
    export type AssignResponsibleMutationError = void

    /**
 * @summary Asignar responsable [CC]
 */
export const useAssignResponsible = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignResponsible>>, TError,{processId: string;data: AssignResponsibleRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof assignResponsible>>,
        TError,
        {processId: string;data: AssignResponsibleRequestDto},
        TContext
      > => {
      return useMutation(getAssignResponsibleMutationOptions(options), queryClient);
    }
    export type removeResponsibleResponse204 = {
  data: void
  status: 204
}

export type removeResponsibleResponse403 = {
  data: void
  status: 403
}

export type removeResponsibleResponse404 = {
  data: void
  status: 404
}

export type removeResponsibleResponse409 = {
  data: void
  status: 409
}

export type removeResponsibleResponseSuccess = (removeResponsibleResponse204) & {
  headers: Headers;
};
export type removeResponsibleResponseError = (removeResponsibleResponse403 | removeResponsibleResponse404 | removeResponsibleResponse409) & {
  headers: Headers;
};

export type removeResponsibleResponse = (removeResponsibleResponseSuccess | removeResponsibleResponseError)

export const getRemoveResponsibleUrl = (processId: string,) => {




  return `/api/v1/processes/${processId}/responsible`
}

/**
 * Revoca la asignación activa del proceso.
 * @summary Quitar responsable
 */
export const removeResponsible = async (processId: string, options?: Parameters<typeof customFetch>[1]): Promise<removeResponsibleResponse> => {

  return customFetch<removeResponsibleResponse>(getRemoveResponsibleUrl(processId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getRemoveResponsibleMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeResponsible>>, TError,{processId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof removeResponsible>>, TError,{processId: string}, TContext> => {

const mutationKey = ['removeResponsible'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeResponsible>>, {processId: string}> = (props) => {
          const {processId} = props ?? {};

          return  removeResponsible(processId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemoveResponsibleMutationResult = NonNullable<Awaited<ReturnType<typeof removeResponsible>>>

    export type RemoveResponsibleMutationError = void

    /**
 * @summary Quitar responsable
 */
export const useRemoveResponsible = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeResponsible>>, TError,{processId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeResponsible>>,
        TError,
        {processId: string},
        TContext
      > => {
      return useMutation(getRemoveResponsibleMutationOptions(options), queryClient);
    }
    export type listProcessesResponse200 = {
  data: ProcessSummaryResponseDto[]
  status: 200
}

export type listProcessesResponse401 = {
  data: void
  status: 401
}

export type listProcessesResponse403 = {
  data: void
  status: 403
}

export type listProcessesResponseSuccess = (listProcessesResponse200) & {
  headers: Headers;
};
export type listProcessesResponseError = (listProcessesResponse401 | listProcessesResponse403) & {
  headers: Headers;
};

export type listProcessesResponse = (listProcessesResponseSuccess | listProcessesResponseError)

export const getListProcessesUrl = () => {




  return `/api/v1/processes`
}

/**
 * JD/TD ven todos; CC solo procesos de su carrera asignada (FSD-UC-019).
 * @summary Listar procesos de acreditación
 */
export const listProcesses = async ( options?: Parameters<typeof customFetch>[1]): Promise<listProcessesResponse> => {

  return customFetch<listProcessesResponse>(getListProcessesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListProcessesQueryKey = () => {
    return [
    `/api/v1/processes`
    ] as const;
    }


export const getListProcessesQueryOptions = <TData = Awaited<ReturnType<typeof listProcesses>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProcesses>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListProcessesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listProcesses>>> = ({ signal }) => listProcesses({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listProcesses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListProcessesQueryResult = NonNullable<Awaited<ReturnType<typeof listProcesses>>>
export type ListProcessesQueryError = void


export function useListProcesses<TData = Awaited<ReturnType<typeof listProcesses>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProcesses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProcesses>>,
          TError,
          Awaited<ReturnType<typeof listProcesses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProcesses<TData = Awaited<ReturnType<typeof listProcesses>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProcesses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProcesses>>,
          TError,
          Awaited<ReturnType<typeof listProcesses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProcesses<TData = Awaited<ReturnType<typeof listProcesses>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProcesses>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar procesos de acreditación
 */

export function useListProcesses<TData = Awaited<ReturnType<typeof listProcesses>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProcesses>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListProcessesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createProcessResponse201 = {
  data: ProcessResponseDto
  status: 201
}

export type createProcessResponse400 = {
  data: void
  status: 400
}

export type createProcessResponse403 = {
  data: void
  status: 403
}

export type createProcessResponse404 = {
  data: void
  status: 404
}

export type createProcessResponse409 = {
  data: void
  status: 409
}

export type createProcessResponseSuccess = (createProcessResponse201) & {
  headers: Headers;
};
export type createProcessResponseError = (createProcessResponse400 | createProcessResponse403 | createProcessResponse404 | createProcessResponse409) & {
  headers: Headers;
};

export type createProcessResponse = (createProcessResponseSuccess | createProcessResponseError)

export const getCreateProcessUrl = () => {




  return `/api/v1/processes`
}

/**
 * Inicia un proceso clonando la taxonomía de una plantilla (Fase -> Subfase).
 * @summary Crear un nuevo proceso
 */
export const createProcess = async (createProcessRequestDto: CreateProcessRequestDto, options?: Parameters<typeof customFetch>[1]): Promise<createProcessResponse> => {

  return customFetch<createProcessResponse>(getCreateProcessUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createProcessRequestDto)
  }
);}





export const getCreateProcessMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProcess>>, TError,{data: CreateProcessRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createProcess>>, TError,{data: CreateProcessRequestDto}, TContext> => {

const mutationKey = ['createProcess'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProcess>>, {data: CreateProcessRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  createProcess(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateProcessMutationResult = NonNullable<Awaited<ReturnType<typeof createProcess>>>
    export type CreateProcessMutationBody = CreateProcessRequestDto
    export type CreateProcessMutationError = void

    /**
 * @summary Crear un nuevo proceso
 */
export const useCreateProcess = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProcess>>, TError,{data: CreateProcessRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProcess>>,
        TError,
        {data: CreateProcessRequestDto},
        TContext
      > => {
      return useMutation(getCreateProcessMutationOptions(options), queryClient);
    }
    export type getProcessResponse200 = {
  data: ProcessResponseDto
  status: 200
}

export type getProcessResponse401 = {
  data: void
  status: 401
}

export type getProcessResponse403 = {
  data: void
  status: 403
}

export type getProcessResponse404 = {
  data: void
  status: 404
}

export type getProcessResponseSuccess = (getProcessResponse200) & {
  headers: Headers;
};
export type getProcessResponseError = (getProcessResponse401 | getProcessResponse403 | getProcessResponse404) & {
  headers: Headers;
};

export type getProcessResponse = (getProcessResponseSuccess | getProcessResponseError)

export const getGetProcessUrl = (processId: string,) => {




  return `/api/v1/processes/${processId}`
}

/**
 * Incluye árbol Fase -> Subfase ordenado por order.
 * @summary Detalle de proceso
 */
export const getProcess = async (processId: string, options?: Parameters<typeof customFetch>[1]): Promise<getProcessResponse> => {

  return customFetch<getProcessResponse>(getGetProcessUrl(processId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetProcessQueryKey = (processId: string,) => {
    return [
    `/api/v1/processes/${processId}`
    ] as const;
    }


export const getGetProcessQueryOptions = <TData = Awaited<ReturnType<typeof getProcess>>, TError = void>(processId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProcess>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProcessQueryKey(processId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProcess>>> = ({ signal }) => getProcess(processId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: processId !== null && processId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProcess>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProcessQueryResult = NonNullable<Awaited<ReturnType<typeof getProcess>>>
export type GetProcessQueryError = void


export function useGetProcess<TData = Awaited<ReturnType<typeof getProcess>>, TError = void>(
 processId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProcess>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProcess>>,
          TError,
          Awaited<ReturnType<typeof getProcess>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProcess<TData = Awaited<ReturnType<typeof getProcess>>, TError = void>(
 processId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProcess>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProcess>>,
          TError,
          Awaited<ReturnType<typeof getProcess>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProcess<TData = Awaited<ReturnType<typeof getProcess>>, TError = void>(
 processId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProcess>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Detalle de proceso
 */

export function useGetProcess<TData = Awaited<ReturnType<typeof getProcess>>, TError = void>(
 processId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProcess>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProcessQueryOptions(processId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type listCandidatesResponse200 = {
  data: EligibleResponsibleDto[]
  status: 200
}

export type listCandidatesResponse403 = {
  data: void
  status: 403
}

export type listCandidatesResponse404 = {
  data: void
  status: 404
}

export type listCandidatesResponseSuccess = (listCandidatesResponse200) & {
  headers: Headers;
};
export type listCandidatesResponseError = (listCandidatesResponse403 | listCandidatesResponse404) & {
  headers: Headers;
};

export type listCandidatesResponse = (listCandidatesResponseSuccess | listCandidatesResponseError)

export const getListCandidatesUrl = (processId: string,) => {




  return `/api/v1/processes/${processId}/responsible/candidates`
}

/**
 * Coordinadores elegibles para el proceso según carrera y disponibilidad.
 * @summary Listar candidatos [CC]
 */
export const listCandidates = async (processId: string, options?: Parameters<typeof customFetch>[1]): Promise<listCandidatesResponse> => {

  return customFetch<listCandidatesResponse>(getListCandidatesUrl(processId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListCandidatesQueryKey = (processId: string,) => {
    return [
    `/api/v1/processes/${processId}/responsible/candidates`
    ] as const;
    }


export const getListCandidatesQueryOptions = <TData = Awaited<ReturnType<typeof listCandidates>>, TError = void>(processId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCandidates>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCandidatesQueryKey(processId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCandidates>>> = ({ signal }) => listCandidates(processId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: processId !== null && processId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCandidates>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCandidatesQueryResult = NonNullable<Awaited<ReturnType<typeof listCandidates>>>
export type ListCandidatesQueryError = void


export function useListCandidates<TData = Awaited<ReturnType<typeof listCandidates>>, TError = void>(
 processId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCandidates>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCandidates>>,
          TError,
          Awaited<ReturnType<typeof listCandidates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCandidates<TData = Awaited<ReturnType<typeof listCandidates>>, TError = void>(
 processId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCandidates>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCandidates>>,
          TError,
          Awaited<ReturnType<typeof listCandidates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCandidates<TData = Awaited<ReturnType<typeof listCandidates>>, TError = void>(
 processId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCandidates>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar candidatos [CC]
 */

export function useListCandidates<TData = Awaited<ReturnType<typeof listCandidates>>, TError = void>(
 processId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCandidates>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCandidatesQueryOptions(processId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






