/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  PhaseCompleteResponseDto
} from '../../model';

import { customFetch } from '../../../lib/api/customFetch.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type completePhaseResponse200 = {
  data: PhaseCompleteResponseDto
  status: 200
}

export type completePhaseResponseSuccess = (completePhaseResponse200) & {
  headers: Headers;
};
;

export type completePhaseResponse = (completePhaseResponseSuccess)

export const getCompletePhaseUrl = (processId: string,
    phaseId: string,) => {




  return `/api/v1/processes/${processId}/phases/${phaseId}/complete`
}

/**
 * @summary Cerrar fase cuando todas las subfases están APROBADO
 */
export const completePhase = async (processId: string,
    phaseId: string, options?: Parameters<typeof customFetch>[1]): Promise<completePhaseResponse> => {

  return customFetch<completePhaseResponse>(getCompletePhaseUrl(processId,phaseId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getCompletePhaseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completePhase>>, TError,{processId: string;phaseId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof completePhase>>, TError,{processId: string;phaseId: string}, TContext> => {

const mutationKey = ['completePhase'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completePhase>>, {processId: string;phaseId: string}> = (props) => {
          const {processId,phaseId} = props ?? {};

          return  completePhase(processId,phaseId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CompletePhaseMutationResult = NonNullable<Awaited<ReturnType<typeof completePhase>>>

    export type CompletePhaseMutationError = unknown

    /**
 * @summary Cerrar fase cuando todas las subfases están APROBADO
 */
export const useCompletePhase = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completePhase>>, TError,{processId: string;phaseId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completePhase>>,
        TError,
        {processId: string;phaseId: string},
        TContext
      > => {
      return useMutation(getCompletePhaseMutationOptions(options), queryClient);
    }
