/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  EvidenceResponse,
  UploadEvidenceBody,
  UploadEvidenceParams
} from '../../model';

import { customFetch } from '../../../lib/api/customFetch';




export type uploadEvidenceResponse200 = {
  data: EvidenceResponse
  status: 200
}

export type uploadEvidenceResponseSuccess = (uploadEvidenceResponse200) & {
  headers: Headers;
};
;

export type uploadEvidenceResponse = (uploadEvidenceResponseSuccess)

export const getUploadEvidenceUrl = (indicatorId: string,
    params: UploadEvidenceParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/indicators/${indicatorId}/evidences?${stringifiedParams}` : `/api/v1/indicators/${indicatorId}/evidences`
}

export const uploadEvidence = async (indicatorId: string,
    params: UploadEvidenceParams,
    uploadEvidenceBody?: UploadEvidenceBody, options?: RequestInit): Promise<uploadEvidenceResponse> => {
    const formData = new FormData();
    if (uploadEvidenceBody?.file !== undefined) {
      const file = uploadEvidenceBody.file;
      const filename = file instanceof File ? file.name : 'evidence';
      formData.append('file', file, filename);
    }
    formData.append('criterionId', params.criterionId);
    if (params.description !== undefined && params.description !== '') {
      formData.append('description', params.description);
    }

  return customFetch<uploadEvidenceResponse>(`/api/v1/indicators/${indicatorId}/evidences`,
  {
    ...options,
    method: 'POST',
    body: formData
  }
);}




export const getUploadEvidenceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadEvidence>>, TError,{indicatorId: string;params: UploadEvidenceParams;data?: UploadEvidenceBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof uploadEvidence>>, TError,{indicatorId: string;params: UploadEvidenceParams;data?: UploadEvidenceBody}, TContext> => {

const mutationKey = ['uploadEvidence'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadEvidence>>, {indicatorId: string;params: UploadEvidenceParams;data?: UploadEvidenceBody}> = (props) => {
          const {indicatorId,params,data} = props ?? {};

          return  uploadEvidence(indicatorId,params,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UploadEvidenceMutationResult = NonNullable<Awaited<ReturnType<typeof uploadEvidence>>>
    export type UploadEvidenceMutationBody = UploadEvidenceBody | undefined
    export type UploadEvidenceMutationError = unknown

    export const useUploadEvidence = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadEvidence>>, TError,{indicatorId: string;params: UploadEvidenceParams;data?: UploadEvidenceBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadEvidence>>,
        TError,
        {indicatorId: string;params: UploadEvidenceParams;data?: UploadEvidenceBody},
        TContext
      > => {
      return useMutation(getUploadEvidenceMutationOptions(options), queryClient);
    }
