/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  Level1CompleteResponseDto
} from '../../model';

import { customFetch } from '../../../lib/api/customFetch.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type completeLevel1Response200 = {
  data: Level1CompleteResponseDto
  status: 200
}

export type completeLevel1ResponseSuccess = (completeLevel1Response200) & {
  headers: Headers;
};
;

export type completeLevel1Response = (completeLevel1ResponseSuccess)

export const getCompleteLevel1Url = (processId: string,
    level1Id: string,) => {




  return `/api/v1/processes/${processId}/level1-nodes/${level1Id}/complete`
}

/**
 * @summary Cerrar Nivel 1 cuando todos los indicadores del subárbol están APROBADO
 */
export const completeLevel1 = async (processId: string,
    level1Id: string, options?: Parameters<typeof customFetch>[1]): Promise<completeLevel1Response> => {

  return customFetch<completeLevel1Response>(getCompleteLevel1Url(processId,level1Id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getCompleteLevel1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeLevel1>>, TError,{processId: string;level1Id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof completeLevel1>>, TError,{processId: string;level1Id: string}, TContext> => {

const mutationKey = ['completeLevel1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeLevel1>>, {processId: string;level1Id: string}> = (props) => {
          const {processId,level1Id} = props ?? {};

          return  completeLevel1(processId,level1Id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CompleteLevel1MutationResult = NonNullable<Awaited<ReturnType<typeof completeLevel1>>>

    export type CompleteLevel1MutationError = unknown

    /**
 * @summary Cerrar Nivel 1 cuando todos los indicadores del subárbol están APROBADO
 */
export const useCompleteLevel1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeLevel1>>, TError,{processId: string;level1Id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeLevel1>>,
        TError,
        {processId: string;level1Id: string},
        TContext
      > => {
      return useMutation(getCompleteLevel1MutationOptions(options), queryClient);
    }
