/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  CreateProcessRequest,
  ProcessResponse
} from '../../model';

import { customFetch } from '../../../lib/api/customFetch';


export type createProcessResponse200 = {
  data: ProcessResponse
  status: 200
}

export type createProcessResponseSuccess = (createProcessResponse200) & {
  headers: Headers;
};
;

export type createProcessResponse = (createProcessResponseSuccess)

export const getCreateProcessUrl = () => {




  return `/api/v1/processes`
}

export const createProcess = async (createProcessRequest: CreateProcessRequest, options?: RequestInit): Promise<createProcessResponse> => {
  const res = await customFetch<ProcessResponse>(getCreateProcessUrl(), {
    ...options,
    method: 'POST',
    body: JSON.stringify(createProcessRequest),
  });

  return { data: res.data, status: res.status as 200, headers: res.headers };
}




export const getCreateProcessMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProcess>>, TError,{data: CreateProcessRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createProcess>>, TError,{data: CreateProcessRequest}, TContext> => {

const mutationKey = ['createProcess'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProcess>>, {data: CreateProcessRequest}> = (props) => {
          const {data} = props ?? {};

          return  createProcess(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateProcessMutationResult = NonNullable<Awaited<ReturnType<typeof createProcess>>>
    export type CreateProcessMutationBody = CreateProcessRequest
    export type CreateProcessMutationError = unknown

    export const useCreateProcess = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProcess>>, TError,{data: CreateProcessRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProcess>>,
        TError,
        {data: CreateProcessRequest},
        TContext
      > => {
      return useMutation(getCreateProcessMutationOptions(options), queryClient);
    }
