/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  QueryFunction,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  RegisterUserRequest,
  RegisterUserResponse,
  UserAdminSummaryResponse
} from '../../model';

import { customFetch } from '../../../lib/api/customFetch';

export interface ListUsersParams {
  role?: string;
  status?: string;
}

export type listUsersResponse200 = {
  data: UserAdminSummaryResponse[];
  status: 200;
};

export const getListUsersUrl = (params?: ListUsersParams) => {
  const search = new URLSearchParams();
  if (params?.role) {
    search.set('role', params.role);
  }
  if (params?.status) {
    search.set('status', params.status);
  }
  const query = search.toString();
  return query.length > 0 ? `/api/v1/admin/users?${query}` : `/api/v1/admin/users`;
};

export const listUsers = async (
  params?: ListUsersParams,
  options?: RequestInit,
): Promise<listUsersResponse200> => {
  const res = await customFetch<UserAdminSummaryResponse[]>(getListUsersUrl(params), {
    ...options,
    method: 'GET',
  });

  return { data: res.data, status: res.status as 200 };
};

export const getListUsersQueryKey = (params?: ListUsersParams) =>
  ['listUsers', params?.role ?? null, params?.status ?? null] as const;

export const getListUsersQueryOptions = <TError = unknown>(
  params?: ListUsersParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError>>; fetch?: RequestInit },
) => {
  const queryKey = getListUsersQueryKey(params);
  const queryFn: QueryFunction<Awaited<ReturnType<typeof listUsers>>> = () => listUsers(params, options?.fetch);

  return { queryKey, queryFn, ...options?.query } as UseQueryOptions<
    Awaited<ReturnType<typeof listUsers>>,
    TError
  >;
};

export const useListUsers = <TError = unknown>(
  params?: ListUsersParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError>>; fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<Awaited<ReturnType<typeof listUsers>>, TError> => {
  return useQuery(getListUsersQueryOptions(params, options), queryClient);
};

export type registerResponse200 = {
  data: RegisterUserResponse
  status: 200
}

export type registerResponseSuccess = (registerResponse200) & {
  headers: Headers;
};
;

export type registerResponse = (registerResponseSuccess)

export const getRegisterUrl = () => {




  return `/api/v1/admin/users`
}

export const register = async (registerUserRequest: RegisterUserRequest, options?: RequestInit): Promise<registerResponse> => {
  const res = await customFetch<RegisterUserResponse>(getRegisterUrl(), {
    ...options,
    method: 'POST',
    body: JSON.stringify(registerUserRequest),
  });

  return { data: res.data, status: res.status as 200, headers: res.headers };
}




export const getRegisterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterUserRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterUserRequest}, TContext> => {

const mutationKey = ['register'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof register>>, {data: RegisterUserRequest}> = (props) => {
          const {data} = props ?? {};

          return  register(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>
    export type RegisterMutationBody = RegisterUserRequest
    export type RegisterMutationError = unknown

    export const useRegister = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterUserRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof register>>,
        TError,
        {data: RegisterUserRequest},
        TContext
      > => {
      return useMutation(getRegisterMutationOptions(options), queryClient);
    }
    export type deactivateResponse200 = {
  data: void
  status: 200
}

export type deactivateResponseSuccess = (deactivateResponse200) & {
  headers: Headers;
};
;

export type deactivateResponse = (deactivateResponseSuccess)

export const getDeactivateUrl = (id: string,) => {




  return `/api/v1/admin/users/${id}/deactivate`
}

export const deactivate = async (id: string, options?: RequestInit): Promise<deactivateResponse> => {
  const res = await customFetch<void>(getDeactivateUrl(id), {
    ...options,
    method: 'PATCH',
  });

  return { data: res.data, status: res.status as 200, headers: res.headers };
}




export const getDeactivateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivate>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deactivate>>, TError,{id: string}, TContext> => {

const mutationKey = ['deactivate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deactivate>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deactivate(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeactivateMutationResult = NonNullable<Awaited<ReturnType<typeof deactivate>>>

    export type DeactivateMutationError = unknown

    export const useDeactivate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivate>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deactivate>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeactivateMutationOptions(options), queryClient);
    }
