/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  RegisterUserRequest,
  RegisterUserResponse
} from '../../model';

import { customFetch } from '../../../lib/api/customFetch';


export type registerResponse200 = {
  data: RegisterUserResponse
  status: 200
}

export type registerResponseSuccess = (registerResponse200) & {
  headers: Headers;
};
;

export type registerResponse = (registerResponseSuccess)

export const getRegisterUrl = () => {




  return `/api/v1/admin/users`
}

export const register = async (registerUserRequest: RegisterUserRequest, options?: RequestInit): Promise<registerResponse> => {
  const res = await customFetch<RegisterUserResponse>(getRegisterUrl(), {
    ...options,
    method: 'POST',
    body: JSON.stringify(registerUserRequest),
  });

  return { data: res.data, status: res.status as 200, headers: res.headers };
}




export const getRegisterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterUserRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterUserRequest}, TContext> => {

const mutationKey = ['register'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof register>>, {data: RegisterUserRequest}> = (props) => {
          const {data} = props ?? {};

          return  register(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>
    export type RegisterMutationBody = RegisterUserRequest
    export type RegisterMutationError = unknown

    export const useRegister = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterUserRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof register>>,
        TError,
        {data: RegisterUserRequest},
        TContext
      > => {
      return useMutation(getRegisterMutationOptions(options), queryClient);
    }
    export type deactivateResponse200 = {
  data: void
  status: 200
}

export type deactivateResponseSuccess = (deactivateResponse200) & {
  headers: Headers;
};
;

export type deactivateResponse = (deactivateResponseSuccess)

export const getDeactivateUrl = (id: string,) => {




  return `/api/v1/admin/users/${id}/deactivate`
}

export const deactivate = async (id: string, options?: RequestInit): Promise<deactivateResponse> => {
  const res = await customFetch<void>(getDeactivateUrl(id), {
    ...options,
    method: 'PATCH',
  });

  return { data: res.data, status: res.status as 200, headers: res.headers };
}




export const getDeactivateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivate>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deactivate>>, TError,{id: string}, TContext> => {

const mutationKey = ['deactivate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deactivate>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deactivate(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeactivateMutationResult = NonNullable<Awaited<ReturnType<typeof deactivate>>>

    export type DeactivateMutationError = unknown

    export const useDeactivate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivate>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deactivate>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeactivateMutationOptions(options), queryClient);
    }
