/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  UploadBody,
  UploadEvidenceResponse,
  UploadParams
} from '../../model';

import { customFetch } from '../../../lib/api/customFetch.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type uploadResponse200 = {
  data: UploadEvidenceResponse
  status: 200
}

export type uploadResponseSuccess = (uploadResponse200) & {
  headers: Headers;
};
;

export type uploadResponse = (uploadResponseSuccess)

export const getUploadUrl = (indicatorId: string,
    params: UploadParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/indicators/${indicatorId}/evidences?${stringifiedParams}` : `/api/v1/indicators/${indicatorId}/evidences`
}

export const upload = async (indicatorId: string,
    params: UploadParams,
    uploadBody?: UploadBody, options?: Parameters<typeof customFetch>[1]): Promise<uploadResponse> => {
    const formData = new FormData();
if(uploadBody?.file !== undefined) {
 formData.append(`file`, uploadBody.file);
 }

  return customFetch<uploadResponse>(getUploadUrl(indicatorId,params),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}





export const getUploadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upload>>, TError,{indicatorId: string;params: UploadParams;data?: UploadBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof upload>>, TError,{indicatorId: string;params: UploadParams;data?: UploadBody}, TContext> => {

const mutationKey = ['upload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof upload>>, {indicatorId: string;params: UploadParams;data?: UploadBody}> = (props) => {
          const {indicatorId,params,data} = props ?? {};

          return  upload(indicatorId,params,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UploadMutationResult = NonNullable<Awaited<ReturnType<typeof upload>>>
    export type UploadMutationBody = UploadBody | undefined
    export type UploadMutationError = unknown

    export const useUpload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upload>>, TError,{indicatorId: string;params: UploadParams;data?: UploadBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof upload>>,
        TError,
        {indicatorId: string;params: UploadParams;data?: UploadBody},
        TContext
      > => {
      return useMutation(getUploadMutationOptions(options), queryClient);
    }
