/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DeprecatedEndpointResponse
} from '../../model';

import { customFetch } from '../../../lib/api/customFetch.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type uploadResponse410 = {
  data: DeprecatedEndpointResponse
  status: 410
}

;
export type uploadResponseError = (uploadResponse410) & {
  headers: Headers;
};

export type uploadResponse = (uploadResponseError)

export const getUploadUrl = (indicatorId: string,) => {




  return `/api/v1/indicators/${indicatorId}/evidences`
}

/**
 * Retorna 410 Gone. Sucesor: POST /api/v1/subphases/{subphaseId}/evidences (API-EVD-01).
 * @deprecated
 * @summary [Deprecado] Cargar evidencia por indicador
 */
export const upload = async (indicatorId: string, options?: Parameters<typeof customFetch>[1]): Promise<uploadResponse> => {

  return customFetch<uploadResponse>(getUploadUrl(indicatorId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getUploadMutationOptions = <TError = DeprecatedEndpointResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upload>>, TError,{indicatorId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof upload>>, TError,{indicatorId: string}, TContext> => {

const mutationKey = ['upload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof upload>>, {indicatorId: string}> = (props) => {
          const {indicatorId} = props ?? {};

          return  upload(indicatorId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UploadMutationResult = NonNullable<Awaited<ReturnType<typeof upload>>>

    export type UploadMutationError = DeprecatedEndpointResponse

    /**
 * @deprecated
 * @summary [Deprecado] Cargar evidencia por indicador
 */
export const useUpload = <TError = DeprecatedEndpointResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upload>>, TError,{indicatorId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof upload>>,
        TError,
        {indicatorId: string},
        TContext
      > => {
      return useMutation(getUploadMutationOptions(options), queryClient);
    }
