/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  MethodologicalStageResponseDto,
  ObserveStageRequestDto,
  StageDeliverableResponseDto,
  StageGateEvaluationResponseDto
} from '../../model';

import { customFetch } from '../../../lib/api/customFetch.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type submitStageResponse200 = {
  data: MethodologicalStageResponseDto
  status: 200
}

export type submitStageResponseSuccess = (submitStageResponse200) & {
  headers: Headers;
};
;

export type submitStageResponse = (submitStageResponseSuccess)

export const getSubmitStageUrl = (processId: string,
    stageId: string,) => {




  return `/api/v1/processes/${processId}/stages/${stageId}/submit`
}

/**
 * @summary Enviar etapa activa a revisión técnica
 */
export const submitStage = async (processId: string,
    stageId: string, options?: Parameters<typeof customFetch>[1]): Promise<submitStageResponse> => {

  return customFetch<submitStageResponse>(getSubmitStageUrl(processId,stageId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getSubmitStageMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitStage>>, TError,{processId: string;stageId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof submitStage>>, TError,{processId: string;stageId: string}, TContext> => {

const mutationKey = ['submitStage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof submitStage>>, {processId: string;stageId: string}> = (props) => {
          const {processId,stageId} = props ?? {};

          return  submitStage(processId,stageId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SubmitStageMutationResult = NonNullable<Awaited<ReturnType<typeof submitStage>>>

    export type SubmitStageMutationError = unknown

    /**
 * @summary Enviar etapa activa a revisión técnica
 */
export const useSubmitStage = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitStage>>, TError,{processId: string;stageId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof submitStage>>,
        TError,
        {processId: string;stageId: string},
        TContext
      > => {
      return useMutation(getSubmitStageMutationOptions(options), queryClient);
    }
    export type observeStageResponse200 = {
  data: MethodologicalStageResponseDto
  status: 200
}

export type observeStageResponseSuccess = (observeStageResponse200) & {
  headers: Headers;
};
;

export type observeStageResponse = (observeStageResponseSuccess)

export const getObserveStageUrl = (processId: string,
    stageId: string,) => {




  return `/api/v1/processes/${processId}/stages/${stageId}/observe`
}

/**
 * @summary Observar etapa metodológica (devolver a CC)
 */
export const observeStage = async (processId: string,
    stageId: string,
    observeStageRequestDto?: ObserveStageRequestDto, options?: Parameters<typeof customFetch>[1]): Promise<observeStageResponse> => {

  return customFetch<observeStageResponse>(getObserveStageUrl(processId,stageId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(observeStageRequestDto)
  }
);}





export const getObserveStageMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof observeStage>>, TError,{processId: string;stageId: string;data?: ObserveStageRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof observeStage>>, TError,{processId: string;stageId: string;data?: ObserveStageRequestDto}, TContext> => {

const mutationKey = ['observeStage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof observeStage>>, {processId: string;stageId: string;data?: ObserveStageRequestDto}> = (props) => {
          const {processId,stageId,data} = props ?? {};

          return  observeStage(processId,stageId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ObserveStageMutationResult = NonNullable<Awaited<ReturnType<typeof observeStage>>>
    export type ObserveStageMutationBody = ObserveStageRequestDto | undefined
    export type ObserveStageMutationError = unknown

    /**
 * @summary Observar etapa metodológica (devolver a CC)
 */
export const useObserveStage = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof observeStage>>, TError,{processId: string;stageId: string;data?: ObserveStageRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof observeStage>>,
        TError,
        {processId: string;stageId: string;data?: ObserveStageRequestDto},
        TContext
      > => {
      return useMutation(getObserveStageMutationOptions(options), queryClient);
    }
    export type approveDeliverableResponse200 = {
  data: StageDeliverableResponseDto
  status: 200
}

export type approveDeliverableResponseSuccess = (approveDeliverableResponse200) & {
  headers: Headers;
};
;

export type approveDeliverableResponse = (approveDeliverableResponseSuccess)

export const getApproveDeliverableUrl = (processId: string,
    stageId: string,
    deliverableId: string,) => {




  return `/api/v1/processes/${processId}/stages/${stageId}/deliverables/${deliverableId}/approve`
}

/**
 * @summary Aprobar entregable documental de etapa
 */
export const approveDeliverable = async (processId: string,
    stageId: string,
    deliverableId: string, options?: Parameters<typeof customFetch>[1]): Promise<approveDeliverableResponse> => {

  return customFetch<approveDeliverableResponse>(getApproveDeliverableUrl(processId,stageId,deliverableId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getApproveDeliverableMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approveDeliverable>>, TError,{processId: string;stageId: string;deliverableId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof approveDeliverable>>, TError,{processId: string;stageId: string;deliverableId: string}, TContext> => {

const mutationKey = ['approveDeliverable'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof approveDeliverable>>, {processId: string;stageId: string;deliverableId: string}> = (props) => {
          const {processId,stageId,deliverableId} = props ?? {};

          return  approveDeliverable(processId,stageId,deliverableId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ApproveDeliverableMutationResult = NonNullable<Awaited<ReturnType<typeof approveDeliverable>>>

    export type ApproveDeliverableMutationError = unknown

    /**
 * @summary Aprobar entregable documental de etapa
 */
export const useApproveDeliverable = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approveDeliverable>>, TError,{processId: string;stageId: string;deliverableId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof approveDeliverable>>,
        TError,
        {processId: string;stageId: string;deliverableId: string},
        TContext
      > => {
      return useMutation(getApproveDeliverableMutationOptions(options), queryClient);
    }
    export type approveStageResponse200 = {
  data: MethodologicalStageResponseDto
  status: 200
}

export type approveStageResponseSuccess = (approveStageResponse200) & {
  headers: Headers;
};
;

export type approveStageResponse = (approveStageResponseSuccess)

export const getApproveStageUrl = (processId: string,
    stageId: string,) => {




  return `/api/v1/processes/${processId}/stages/${stageId}/approve`
}

/**
 * @summary Aprobar etapa metodológica (exige compuerta PASS)
 */
export const approveStage = async (processId: string,
    stageId: string, options?: Parameters<typeof customFetch>[1]): Promise<approveStageResponse> => {

  return customFetch<approveStageResponse>(getApproveStageUrl(processId,stageId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getApproveStageMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approveStage>>, TError,{processId: string;stageId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof approveStage>>, TError,{processId: string;stageId: string}, TContext> => {

const mutationKey = ['approveStage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof approveStage>>, {processId: string;stageId: string}> = (props) => {
          const {processId,stageId} = props ?? {};

          return  approveStage(processId,stageId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ApproveStageMutationResult = NonNullable<Awaited<ReturnType<typeof approveStage>>>

    export type ApproveStageMutationError = unknown

    /**
 * @summary Aprobar etapa metodológica (exige compuerta PASS)
 */
export const useApproveStage = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approveStage>>, TError,{processId: string;stageId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof approveStage>>,
        TError,
        {processId: string;stageId: string},
        TContext
      > => {
      return useMutation(getApproveStageMutationOptions(options), queryClient);
    }
    export type listStagesResponse200 = {
  data: MethodologicalStageResponseDto[]
  status: 200
}

export type listStagesResponseSuccess = (listStagesResponse200) & {
  headers: Headers;
};
;

export type listStagesResponse = (listStagesResponseSuccess)

export const getListStagesUrl = (processId: string,) => {




  return `/api/v1/processes/${processId}/stages`
}

/**
 * @summary Listar timeline de etapas metodológicas del proceso
 */
export const listStages = async (processId: string, options?: Parameters<typeof customFetch>[1]): Promise<listStagesResponse> => {

  return customFetch<listStagesResponse>(getListStagesUrl(processId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListStagesQueryKey = (processId: string,) => {
    return [
    `/api/v1/processes/${processId}/stages`
    ] as const;
    }


export const getListStagesQueryOptions = <TData = Awaited<ReturnType<typeof listStages>>, TError = unknown>(processId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStages>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListStagesQueryKey(processId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listStages>>> = ({ signal }) => listStages(processId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: processId !== null && processId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listStages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListStagesQueryResult = NonNullable<Awaited<ReturnType<typeof listStages>>>
export type ListStagesQueryError = unknown


export function useListStages<TData = Awaited<ReturnType<typeof listStages>>, TError = unknown>(
 processId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStages>>,
          TError,
          Awaited<ReturnType<typeof listStages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStages<TData = Awaited<ReturnType<typeof listStages>>, TError = unknown>(
 processId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStages>>,
          TError,
          Awaited<ReturnType<typeof listStages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStages<TData = Awaited<ReturnType<typeof listStages>>, TError = unknown>(
 processId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStages>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar timeline de etapas metodológicas del proceso
 */

export function useListStages<TData = Awaited<ReturnType<typeof listStages>>, TError = unknown>(
 processId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStages>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListStagesQueryOptions(processId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type evaluateGateResponse200 = {
  data: StageGateEvaluationResponseDto
  status: 200
}

export type evaluateGateResponseSuccess = (evaluateGateResponse200) & {
  headers: Headers;
};
;

export type evaluateGateResponse = (evaluateGateResponseSuccess)

export const getEvaluateGateUrl = (processId: string,
    stageId: string,) => {




  return `/api/v1/processes/${processId}/stages/${stageId}/gate`
}

/**
 * @summary Preview de compuerta de avance para la etapa
 */
export const evaluateGate = async (processId: string,
    stageId: string, options?: Parameters<typeof customFetch>[1]): Promise<evaluateGateResponse> => {

  return customFetch<evaluateGateResponse>(getEvaluateGateUrl(processId,stageId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getEvaluateGateQueryKey = (processId: string,
    stageId: string,) => {
    return [
    `/api/v1/processes/${processId}/stages/${stageId}/gate`
    ] as const;
    }


export const getEvaluateGateQueryOptions = <TData = Awaited<ReturnType<typeof evaluateGate>>, TError = unknown>(processId: string,
    stageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof evaluateGate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEvaluateGateQueryKey(processId,stageId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof evaluateGate>>> = ({ signal }) => evaluateGate(processId,stageId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: processId !== null && processId !== undefined && stageId !== null && stageId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof evaluateGate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EvaluateGateQueryResult = NonNullable<Awaited<ReturnType<typeof evaluateGate>>>
export type EvaluateGateQueryError = unknown


export function useEvaluateGate<TData = Awaited<ReturnType<typeof evaluateGate>>, TError = unknown>(
 processId: string,
    stageId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof evaluateGate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof evaluateGate>>,
          TError,
          Awaited<ReturnType<typeof evaluateGate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEvaluateGate<TData = Awaited<ReturnType<typeof evaluateGate>>, TError = unknown>(
 processId: string,
    stageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof evaluateGate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof evaluateGate>>,
          TError,
          Awaited<ReturnType<typeof evaluateGate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEvaluateGate<TData = Awaited<ReturnType<typeof evaluateGate>>, TError = unknown>(
 processId: string,
    stageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof evaluateGate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Preview de compuerta de avance para la etapa
 */

export function useEvaluateGate<TData = Awaited<ReturnType<typeof evaluateGate>>, TError = unknown>(
 processId: string,
    stageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof evaluateGate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEvaluateGateQueryOptions(processId,stageId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






