/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EvidenceVersionHistoryResponseDto
} from '../../model';

import { customFetch } from '../../../lib/api/customFetch.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listVersionsResponse200 = {
  data: EvidenceVersionHistoryResponseDto[]
  status: 200
}

export type listVersionsResponseSuccess = (listVersionsResponse200) & {
  headers: Headers;
};
;

export type listVersionsResponse = (listVersionsResponseSuccess)

export const getListVersionsUrl = (evidenceId: string,) => {




  return `/api/v1/evidences/${evidenceId}/versions`
}

/**
 * @summary Listar historial de versiones de una evidencia
 */
export const listVersions = async (evidenceId: string, options?: Parameters<typeof customFetch>[1]): Promise<listVersionsResponse> => {

  return customFetch<listVersionsResponse>(getListVersionsUrl(evidenceId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListVersionsQueryKey = (evidenceId: string,) => {
    return [
    `/api/v1/evidences/${evidenceId}/versions`
    ] as const;
    }


export const getListVersionsQueryOptions = <TData = Awaited<ReturnType<typeof listVersions>>, TError = unknown>(evidenceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVersions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListVersionsQueryKey(evidenceId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listVersions>>> = ({ signal }) => listVersions(evidenceId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: evidenceId !== null && evidenceId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listVersions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListVersionsQueryResult = NonNullable<Awaited<ReturnType<typeof listVersions>>>
export type ListVersionsQueryError = unknown


export function useListVersions<TData = Awaited<ReturnType<typeof listVersions>>, TError = unknown>(
 evidenceId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVersions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVersions>>,
          TError,
          Awaited<ReturnType<typeof listVersions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVersions<TData = Awaited<ReturnType<typeof listVersions>>, TError = unknown>(
 evidenceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVersions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVersions>>,
          TError,
          Awaited<ReturnType<typeof listVersions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVersions<TData = Awaited<ReturnType<typeof listVersions>>, TError = unknown>(
 evidenceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVersions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar historial de versiones de una evidencia
 */

export function useListVersions<TData = Awaited<ReturnType<typeof listVersions>>, TError = unknown>(
 evidenceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVersions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListVersionsQueryOptions(evidenceId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type _deleteResponse200 = {
  data: void
  status: 200
}

export type _deleteResponseSuccess = (_deleteResponse200) & {
  headers: Headers;
};
;

export type _deleteResponse = (_deleteResponseSuccess)

export const getDeleteUrl = (evidenceId: string,) => {




  return `/api/v1/evidences/${evidenceId}`
}

/**
 * @summary Intento de borrado (siempre rechazado si existe — append-only)
 */
export const _delete = async (evidenceId: string, options?: Parameters<typeof customFetch>[1]): Promise<_deleteResponse> => {

  return customFetch<_deleteResponse>(getDeleteUrl(evidenceId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof _delete>>, TError,{evidenceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof _delete>>, TError,{evidenceId: string}, TContext> => {

const mutationKey = ['_delete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof _delete>>, {evidenceId: string}> = (props) => {
          const {evidenceId} = props ?? {};

          return  _delete(evidenceId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type _DeleteMutationResult = NonNullable<Awaited<ReturnType<typeof _delete>>>

    export type _DeleteMutationError = unknown

    /**
 * @summary Intento de borrado (siempre rechazado si existe — append-only)
 */
export const useDelete = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof _delete>>, TError,{evidenceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof _delete>>,
        TError,
        {evidenceId: string},
        TContext
      > => {
      return useMutation(getDeleteMutationOptions(options), queryClient);
    }
