/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ListTemplatesParams,
  TemplateDetailResponseDto,
  TemplateSummaryResponseDto,
  UpsertTemplateRequestDto
} from '../../model';

import { customFetch } from '../../../lib/api/customFetch.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getTemplateResponse200 = {
  data: TemplateDetailResponseDto
  status: 200
}

export type getTemplateResponseSuccess = (getTemplateResponse200) & {
  headers: Headers;
};
;

export type getTemplateResponse = (getTemplateResponseSuccess)

export const getGetTemplateUrl = (templateId: string,) => {




  return `/api/v1/templates/${templateId}`
}

/**
 * @summary Obtener detalle de plantilla
 */
export const getTemplate = async (templateId: string, options?: Parameters<typeof customFetch>[1]): Promise<getTemplateResponse> => {

  return customFetch<getTemplateResponse>(getGetTemplateUrl(templateId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTemplateQueryKey = (templateId: string,) => {
    return [
    `/api/v1/templates/${templateId}`
    ] as const;
    }


export const getGetTemplateQueryOptions = <TData = Awaited<ReturnType<typeof getTemplate>>, TError = unknown>(templateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTemplateQueryKey(templateId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTemplate>>> = ({ signal }) => getTemplate(templateId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: templateId !== null && templateId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTemplate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTemplateQueryResult = NonNullable<Awaited<ReturnType<typeof getTemplate>>>
export type GetTemplateQueryError = unknown


export function useGetTemplate<TData = Awaited<ReturnType<typeof getTemplate>>, TError = unknown>(
 templateId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTemplate>>,
          TError,
          Awaited<ReturnType<typeof getTemplate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTemplate<TData = Awaited<ReturnType<typeof getTemplate>>, TError = unknown>(
 templateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTemplate>>,
          TError,
          Awaited<ReturnType<typeof getTemplate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTemplate<TData = Awaited<ReturnType<typeof getTemplate>>, TError = unknown>(
 templateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obtener detalle de plantilla
 */

export function useGetTemplate<TData = Awaited<ReturnType<typeof getTemplate>>, TError = unknown>(
 templateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTemplateQueryOptions(templateId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type updateTemplateResponse200 = {
  data: TemplateDetailResponseDto
  status: 200
}

export type updateTemplateResponseSuccess = (updateTemplateResponse200) & {
  headers: Headers;
};
;

export type updateTemplateResponse = (updateTemplateResponseSuccess)

export const getUpdateTemplateUrl = (templateId: string,) => {




  return `/api/v1/templates/${templateId}`
}

/**
 * @summary Actualizar plantilla
 */
export const updateTemplate = async (templateId: string,
    upsertTemplateRequestDto: UpsertTemplateRequestDto, options?: Parameters<typeof customFetch>[1]): Promise<updateTemplateResponse> => {

  return customFetch<updateTemplateResponse>(getUpdateTemplateUrl(templateId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(upsertTemplateRequestDto)
  }
);}





export const getUpdateTemplateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTemplate>>, TError,{templateId: string;data: UpsertTemplateRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateTemplate>>, TError,{templateId: string;data: UpsertTemplateRequestDto}, TContext> => {

const mutationKey = ['updateTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTemplate>>, {templateId: string;data: UpsertTemplateRequestDto}> = (props) => {
          const {templateId,data} = props ?? {};

          return  updateTemplate(templateId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof updateTemplate>>>
    export type UpdateTemplateMutationBody = UpsertTemplateRequestDto
    export type UpdateTemplateMutationError = unknown

    /**
 * @summary Actualizar plantilla
 */
export const useUpdateTemplate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTemplate>>, TError,{templateId: string;data: UpsertTemplateRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTemplate>>,
        TError,
        {templateId: string;data: UpsertTemplateRequestDto},
        TContext
      > => {
      return useMutation(getUpdateTemplateMutationOptions(options), queryClient);
    }
    export type deleteTemplateResponse200 = {
  data: void
  status: 200
}

export type deleteTemplateResponseSuccess = (deleteTemplateResponse200) & {
  headers: Headers;
};
;

export type deleteTemplateResponse = (deleteTemplateResponseSuccess)

export const getDeleteTemplateUrl = (templateId: string,) => {




  return `/api/v1/templates/${templateId}`
}

/**
 * @summary Eliminar plantilla DRAFT sin procesos referenciados
 */
export const deleteTemplate = async (templateId: string, options?: Parameters<typeof customFetch>[1]): Promise<deleteTemplateResponse> => {

  return customFetch<deleteTemplateResponse>(getDeleteTemplateUrl(templateId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteTemplateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTemplate>>, TError,{templateId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTemplate>>, TError,{templateId: string}, TContext> => {

const mutationKey = ['deleteTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTemplate>>, {templateId: string}> = (props) => {
          const {templateId} = props ?? {};

          return  deleteTemplate(templateId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTemplate>>>

    export type DeleteTemplateMutationError = unknown

    /**
 * @summary Eliminar plantilla DRAFT sin procesos referenciados
 */
export const useDeleteTemplate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTemplate>>, TError,{templateId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTemplate>>,
        TError,
        {templateId: string},
        TContext
      > => {
      return useMutation(getDeleteTemplateMutationOptions(options), queryClient);
    }
    export type listTemplatesResponse200 = {
  data: TemplateSummaryResponseDto[]
  status: 200
}

export type listTemplatesResponseSuccess = (listTemplatesResponse200) & {
  headers: Headers;
};
;

export type listTemplatesResponse = (listTemplatesResponseSuccess)

export const getListTemplatesUrl = (params?: ListTemplatesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/templates?${stringifiedParams}` : `/api/v1/templates`
}

/**
 * @summary Listar plantillas normativas
 */
export const listTemplates = async (params?: ListTemplatesParams, options?: Parameters<typeof customFetch>[1]): Promise<listTemplatesResponse> => {

  return customFetch<listTemplatesResponse>(getListTemplatesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListTemplatesQueryKey = (params?: ListTemplatesParams,) => {
    return [
    `/api/v1/templates`, ...(params ? [params] : [])
    ] as const;
    }


export const getListTemplatesQueryOptions = <TData = Awaited<ReturnType<typeof listTemplates>>, TError = unknown>(params?: ListTemplatesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTemplates>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTemplatesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTemplates>>> = ({ signal }) => listTemplates(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTemplates>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTemplatesQueryResult = NonNullable<Awaited<ReturnType<typeof listTemplates>>>
export type ListTemplatesQueryError = unknown


export function useListTemplates<TData = Awaited<ReturnType<typeof listTemplates>>, TError = unknown>(
 params: undefined |  ListTemplatesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTemplates>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTemplates>>,
          TError,
          Awaited<ReturnType<typeof listTemplates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTemplates<TData = Awaited<ReturnType<typeof listTemplates>>, TError = unknown>(
 params?: ListTemplatesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTemplates>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTemplates>>,
          TError,
          Awaited<ReturnType<typeof listTemplates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTemplates<TData = Awaited<ReturnType<typeof listTemplates>>, TError = unknown>(
 params?: ListTemplatesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTemplates>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar plantillas normativas
 */

export function useListTemplates<TData = Awaited<ReturnType<typeof listTemplates>>, TError = unknown>(
 params?: ListTemplatesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTemplates>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTemplatesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createTemplateResponse200 = {
  data: TemplateDetailResponseDto
  status: 200
}

export type createTemplateResponseSuccess = (createTemplateResponse200) & {
  headers: Headers;
};
;

export type createTemplateResponse = (createTemplateResponseSuccess)

export const getCreateTemplateUrl = () => {




  return `/api/v1/templates`
}

/**
 * @summary Crear plantilla en borrador
 */
export const createTemplate = async (upsertTemplateRequestDto: UpsertTemplateRequestDto, options?: Parameters<typeof customFetch>[1]): Promise<createTemplateResponse> => {

  return customFetch<createTemplateResponse>(getCreateTemplateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(upsertTemplateRequestDto)
  }
);}





export const getCreateTemplateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTemplate>>, TError,{data: UpsertTemplateRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createTemplate>>, TError,{data: UpsertTemplateRequestDto}, TContext> => {

const mutationKey = ['createTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTemplate>>, {data: UpsertTemplateRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  createTemplate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof createTemplate>>>
    export type CreateTemplateMutationBody = UpsertTemplateRequestDto
    export type CreateTemplateMutationError = unknown

    /**
 * @summary Crear plantilla en borrador
 */
export const useCreateTemplate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTemplate>>, TError,{data: UpsertTemplateRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTemplate>>,
        TError,
        {data: UpsertTemplateRequestDto},
        TContext
      > => {
      return useMutation(getCreateTemplateMutationOptions(options), queryClient);
    }
    export type publishTemplateResponse200 = {
  data: TemplateDetailResponseDto
  status: 200
}

export type publishTemplateResponseSuccess = (publishTemplateResponse200) & {
  headers: Headers;
};
;

export type publishTemplateResponse = (publishTemplateResponseSuccess)

export const getPublishTemplateUrl = (templateId: string,) => {




  return `/api/v1/templates/${templateId}/publish`
}

/**
 * @summary Publicar plantilla
 */
export const publishTemplate = async (templateId: string, options?: Parameters<typeof customFetch>[1]): Promise<publishTemplateResponse> => {

  return customFetch<publishTemplateResponse>(getPublishTemplateUrl(templateId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPublishTemplateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishTemplate>>, TError,{templateId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof publishTemplate>>, TError,{templateId: string}, TContext> => {

const mutationKey = ['publishTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof publishTemplate>>, {templateId: string}> = (props) => {
          const {templateId} = props ?? {};

          return  publishTemplate(templateId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PublishTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof publishTemplate>>>

    export type PublishTemplateMutationError = unknown

    /**
 * @summary Publicar plantilla
 */
export const usePublishTemplate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishTemplate>>, TError,{templateId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof publishTemplate>>,
        TError,
        {templateId: string},
        TContext
      > => {
      return useMutation(getPublishTemplateMutationOptions(options), queryClient);
    }
    export type duplicateTemplateResponse200 = {
  data: TemplateDetailResponseDto
  status: 200
}

export type duplicateTemplateResponseSuccess = (duplicateTemplateResponse200) & {
  headers: Headers;
};
;

export type duplicateTemplateResponse = (duplicateTemplateResponseSuccess)

export const getDuplicateTemplateUrl = (templateId: string,) => {




  return `/api/v1/templates/${templateId}/duplicate`
}

/**
 * @summary Duplicar plantilla como borrador
 */
export const duplicateTemplate = async (templateId: string, options?: Parameters<typeof customFetch>[1]): Promise<duplicateTemplateResponse> => {

  return customFetch<duplicateTemplateResponse>(getDuplicateTemplateUrl(templateId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getDuplicateTemplateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof duplicateTemplate>>, TError,{templateId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof duplicateTemplate>>, TError,{templateId: string}, TContext> => {

const mutationKey = ['duplicateTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof duplicateTemplate>>, {templateId: string}> = (props) => {
          const {templateId} = props ?? {};

          return  duplicateTemplate(templateId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DuplicateTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof duplicateTemplate>>>

    export type DuplicateTemplateMutationError = unknown

    /**
 * @summary Duplicar plantilla como borrador
 */
export const useDuplicateTemplate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof duplicateTemplate>>, TError,{templateId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof duplicateTemplate>>,
        TError,
        {templateId: string},
        TContext
      > => {
      return useMutation(getDuplicateTemplateMutationOptions(options), queryClient);
    }
    export type archiveTemplateResponse200 = {
  data: TemplateDetailResponseDto
  status: 200
}

export type archiveTemplateResponseSuccess = (archiveTemplateResponse200) & {
  headers: Headers;
};
;

export type archiveTemplateResponse = (archiveTemplateResponseSuccess)

export const getArchiveTemplateUrl = (templateId: string,) => {




  return `/api/v1/templates/${templateId}/archive`
}

/**
 * @summary Archivar plantilla
 */
export const archiveTemplate = async (templateId: string, options?: Parameters<typeof customFetch>[1]): Promise<archiveTemplateResponse> => {

  return customFetch<archiveTemplateResponse>(getArchiveTemplateUrl(templateId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getArchiveTemplateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof archiveTemplate>>, TError,{templateId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof archiveTemplate>>, TError,{templateId: string}, TContext> => {

const mutationKey = ['archiveTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof archiveTemplate>>, {templateId: string}> = (props) => {
          const {templateId} = props ?? {};

          return  archiveTemplate(templateId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ArchiveTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof archiveTemplate>>>

    export type ArchiveTemplateMutationError = unknown

    /**
 * @summary Archivar plantilla
 */
export const useArchiveTemplate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof archiveTemplate>>, TError,{templateId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof archiveTemplate>>,
        TError,
        {templateId: string},
        TContext
      > => {
      return useMutation(getArchiveTemplateMutationOptions(options), queryClient);
    }
