/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface AssistantChatContextDto {
  /** @pattern phases|users|general */
  agent?: string;
  processId?: string;
  careerName?: string;
  careerCode?: string;
  templateType?: string;
  userId?: string;
  programId?: string;
}
