/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ChatMessageDto {
  /** @minLength 1 */
  role: string;
  /** @minLength 1 */
  content: string;
}
