/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CoordinatorKpiSection } from './coordinatorKpiSection.ts';
import type { ExecutiveKpiSection } from './executiveKpiSection.ts';
import type { TechnicianKpiSection } from './technicianKpiSection.ts';

export interface CompositeDashboardSummary {
  userId?: string;
  grantedPermissions?: string[];
  coordinatorSection?: CoordinatorKpiSection;
  technicianSection?: TechnicianKpiSection;
  executiveSection?: ExecutiveKpiSection;
}
