/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { BottleneckSummary } from './bottleneckSummary';
import type { PhaseProgressSummary } from './phaseProgressSummary';

export interface CoordinatorKpiSection {
  programId?: string;
  programName?: string;
  totalIndicators?: number;
  overallProgressPercentage?: number;
  approvedEvidences?: number;
  rejectedEvidences?: number;
  pendingObservations?: number;
  phaseProgressList?: PhaseProgressSummary[];
  bottlenecks?: BottleneckSummary[];
}
