/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CreateNormativeIndicatorRequestDto {
  /** @minLength 1 */
  code: string;
  /** @minLength 1 */
  description: string;
  weight: number;
  order: number;
  /** @minLength 1 */
  referenceUrl: string;
}
