/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CreateProcessRequestType = typeof CreateProcessRequestType[keyof typeof CreateProcessRequestType];


export const CreateProcessRequestType = {
  CEUB: 'CEUB',
  ARCU_SUR: 'ARCU_SUR',
} as const;
