/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CreatePhaseRequestDto {
  /** @minLength 1 */
  name: string;
  order: number;
  description?: string;
}
