/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CreateProcessRequestType } from './createProcessRequestType';

export interface CreateProcessRequest {
  templateId?: string;
  careerId?: string;
  period?: string;
  type?: CreateProcessRequestType;
}
