/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Respuesta de endpoint retirado (HTTP 410)
 */
export interface DeprecatedEndpointResponse {
  error?: string;
  message?: string;
  /** Identificador legacy recibido en la ruta */
  indicatorId?: string;
}
