/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Respuesta de endpoint retirado (HTTP 410)
 */
export interface DeprecatedEndpointResponseDto {
  /** @example ENDPOINT_DEPRECATED */
  error?: string;
  /** @example La carga por indicador fue retirada. Use POST /api/v1/subphases/{subphaseId}/evidences. */
  message?: string;
  /** Identificador legacy recibido en la ruta */
  indicatorId?: string;
}
