/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface EvidenceSearchDetailDto {
  evidenceId?: string;
  title?: string;
  description?: string;
  dimensionName?: string;
  criterionCode?: string;
  carreraName?: string;
  uploadedAt?: string;
}
