/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { EvidenceSearchHitResponseDto } from './evidenceSearchHitResponseDto.ts';

export interface EvidenceSearchPageResponseDto {
  items?: EvidenceSearchHitResponseDto[];
  total?: number;
  page?: number;
  size?: number;
}
