/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface EvidenceSearchHitResponseDto {
  evidenceId?: string;
  subphaseId?: string;
  subphaseName?: string;
  phaseId?: string;
  phaseName?: string;
  processId?: string;
  indicatorId?: string;
  indicatorCode?: string;
  indicatorTitle?: string;
  version?: number;
  description?: string;
  originalFilename?: string;
  uploadedAt?: string;
  uploadedBy?: string;
  blobAvailable?: boolean;
}
