/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface EvidenceVersionHistoryResponseDto {
  versionId?: string;
  version?: number;
  supersedesVersion?: number;
  observationId?: string;
  description?: string;
  contentHash?: string;
  originalFilename?: string;
  createdBy?: string;
  createdAt?: string;
  current?: boolean;
  blobAvailable?: boolean;
}
