/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProgramTrafficLight } from './programTrafficLight';

export interface ExecutiveKpiSection {
  totalPrograms?: number;
  averageGlobalProgress?: number;
  criticalObservations?: number;
  alertPrograms?: number;
  programTrafficLights?: ProgramTrafficLight[];
}
