/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Pageable } from './pageable.ts';

export type GetCoordinatorDetailsParams = {
phaseId?: number;
status?: string;
pageable: Pageable;
};
