/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface IndicatorWorkflowResponseDto {
  indicatorId?: string;
  previousState?: string;
  newState?: string;
  stateHistoryId?: string;
  observationId?: string;
  event?: string;
}
