/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface JobStatusResponse {
  jobId?: string;
  status?: string;
  progressPercentage?: number;
  downloadUrl?: string;
  errorMessage?: string;
}
