/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Level1CompleteResponseDto {
  level1Id?: string;
  previousState?: string;
  newState?: string;
  event?: string;
}
