/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type List1Params = {
/**
 * Texto de búsqueda (nombre o código)
 */
q?: string;
};
