/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface LoginResponse {
  accessToken?: string;
  expiresIn?: number;
  role?: string;
  programScope?: string[];
}
