/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface NormativeIndicatorDto {
  id?: string;
  code?: string;
  description?: string;
  weight?: number;
  order?: number;
  status?: string;
  referenceUrl?: string;
}
