/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface NormativeIndicatorDetailResponseDto {
  id?: string;
  processId?: string;
  careerId?: string;
  level1Id?: string;
  level1Name?: string;
  code?: string;
  description?: string;
  weight?: number;
  order?: number;
  status?: string;
  referenceUrl?: string;
  normativePath?: string[];
}
