/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ObservationSummary } from './observationSummary.ts';
import type { PageableObject } from './pageableObject.ts';
import type { SortObject } from './sortObject.ts';

export interface PageObservationSummary {
  totalPages?: number;
  totalElements?: number;
  pageable?: PageableObject;
  size?: number;
  content?: ObservationSummary[];
  number?: number;
  sort?: SortObject;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  empty?: boolean;
}
