/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SortObject } from './sortObject.ts';

export interface PageableObject {
  unpaged?: boolean;
  paged?: boolean;
  pageSize?: number;
  pageNumber?: number;
  offset?: number;
  sort?: SortObject;
}
