/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PendingIndicatorResponseDto {
  indicatorId?: string;
  programId?: string;
  criterionId?: string;
  currentState?: string;
  evidenceId?: string;
  versionNumber?: number;
  contentHash?: string;
  description?: string;
}
