/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PhaseCompleteResponseDto {
  phaseId?: string;
  previousState?: string;
  newState?: string;
  event?: string;
}
