/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SubphaseDto } from './subphaseDto';

export interface PhaseDto {
  id?: string;
  name?: string;
  order?: number;
  subphases?: SubphaseDto[];
}
