/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SubphaseDto } from './subphaseDto.ts';

export interface PhaseDto {
  id?: string;
  name?: string;
  order?: number;
  description?: string;
  subphases?: SubphaseDto[];
}
