/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ProcessSummaryResponseDto {
  id?: string;
  careerId?: string;
  careerCode?: string;
  careerName?: string;
  templateId?: string;
  templateName?: string;
  templateType?: string;
  status?: string;
  startDate?: string;
  phaseCount?: number;
  subphaseCount?: number;
}
