/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PhaseDto } from './phaseDto';

export interface ProcessResponseDto {
  id?: string;
  careerId?: string;
  status?: string;
  startDate?: string;
  phases?: PhaseDto[];
}
