/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { NormativeLevel1NodeDto } from './normativeLevel1NodeDto.ts';
import type { ProcessResponsibleDto } from './processResponsibleDto.ts';

export interface ProcessResponseDto {
  id?: string;
  careerId?: string;
  careerCode?: string;
  careerName?: string;
  templateId?: string;
  templateName?: string;
  templateType?: string;
  evaluatorModel?: string;
  status?: string;
  startDate?: string;
  level1Nodes?: NormativeLevel1NodeDto[];
  responsible?: ProcessResponsibleDto;
}
