/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProcessResponsibleDto } from './processResponsibleDto.ts';

export interface ProcessSummaryResponseDto {
  id?: string;
  careerId?: string;
  careerCode?: string;
  careerName?: string;
  templateId?: string;
  templateName?: string;
  templateType?: string;
  evaluatorModel?: string;
  status?: string;
  startDate?: string;
  level1Count?: number;
  indicatorCount?: number;
  responsible?: ProcessResponsibleDto;
}
