/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ProgramSummaryResponse {
  id?: string;
  code?: string;
  name?: string;
}
