/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface RecentEvaluation {
  evidenceId?: string;
  program?: string;
  revisionDate?: string;
  result?: string;
}
