/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface RegisterUserRequest {
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  role: string;
  programId?: string;
  /** @minLength 1 */
  firstName: string;
  /** @minLength 1 */
  lastName: string;
  /**
     * @minLength 1
     * @pattern ^[67]\d{7}$
     */
  phoneNumber: string;
  /**
     * @minLength 8
     * @maxLength 2147483647
     */
  password: string;
}
