/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface RejectIndicatorRequestDto {
  /**
     * @minLength 20
     * @maxLength 4000
     */
  justification: string;
}
