/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ReorderStructureRequestDtoSubphasesByPhase } from './reorderStructureRequestDtoSubphasesByPhase.ts';

export interface ReorderStructureRequestDto {
  phases?: string[];
  subphasesByPhase?: ReorderStructureRequestDtoSubphasesByPhase;
}
