/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { EvidenceSearchDetailDto } from './evidenceSearchDetailDto.ts';

export interface SearchQueryResponseDto {
  query?: string;
  routingPath?: string;
  toolUsed?: string;
  dataSource?: string;
  message?: string;
  results?: EvidenceSearchDetailDto[];
  sqlQuery?: string;
  llmThought?: string;
}
