/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type SearchParams = {
processId?: string;
level1Id?: string;
indicatorId?: string;
programId?: string;
q?: string;
managementYear?: number;
page?: number;
size?: number;
};
