/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SearchSubsetDto } from './searchSubsetDto.ts';

export interface SearchQueryResponseDto {
  query?: string;
  routingPath?: string;
  subsets?: SearchSubsetDto[];
  message?: string;
  llmThought?: string;
}
