/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AssistantChatContextDto } from './assistantChatContextDto.ts';
import type { ChatMessageDto } from './chatMessageDto.ts';

export interface SendChatMessageRequest {
  /** @minLength 1 */
  message: string;
  history?: ChatMessageDto[];
  context?: AssistantChatContextDto;
}
