/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AssistantToolStepResponse } from './assistantToolStepResponse.ts';

export interface SendChatMessageResponse {
  reply?: string;
  toolId?: string;
  sourceTables?: string[];
  path?: string;
  llmInvoked?: boolean;
  steps?: AssistantToolStepResponse[];
}
