/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface StageDeliverableResponseDto {
  id?: string;
  stageId?: string;
  deliverableCode?: string;
  approvalStatus?: string;
  approvedBy?: string;
  technicalObservations?: string;
  approvedAt?: string;
}
