/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface SubphaseEvidenceResponseDto {
  evidenceId?: string;
  subphaseId?: string;
  indicatorId?: string;
  version?: number;
  description?: string;
  contentHash?: string;
  originalFilename?: string;
  uploadedAt?: string;
  uploadedBy?: string;
}
