/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface SubphaseObservationResponseDto {
  id?: string;
  subphaseId?: string;
  authorId?: string;
  authorRole?: string;
  body?: string;
  status?: string;
  resolvedAt?: string;
  resolvedVersionId?: string;
  createdAt?: string;
  updatedAt?: string;
}
