/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SubphaseTransitionResponseDto } from './subphaseTransitionResponseDto.ts';

export interface SubphaseApproveResponseDto {
  subphaseId?: string;
  transition?: SubphaseTransitionResponseDto;
}
