/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type SubsanateEvidenceBody = {
  file: Blob;
  description: string;
  observationId: string;
};
