/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RecentEvaluation } from './recentEvaluation';

export interface TechnicianKpiSection {
  evidencesPendingReview?: number;
  assignedIndicators?: number;
  openActions?: number;
  available?: number;
  recentEvaluations?: RecentEvaluation[];
}
