/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { NormativeLevel1NodeDto } from './normativeLevel1NodeDto.ts';
import type { TemplatePhaseResponseDto } from './templatePhaseResponseDto.ts';

export interface TemplateDetailResponseDto {
  id?: string;
  name?: string;
  description?: string;
  type?: string;
  status?: string;
  phaseCount?: number;
  subphaseCount?: number;
  level1Count?: number;
  indicatorCount?: number;
  evaluatorModel?: string;
  createdAt?: string;
  updatedAt?: string;
  phases?: TemplatePhaseResponseDto[];
  level1Nodes?: NormativeLevel1NodeDto[];
}
