/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TemplateSubphaseRequestDto } from './templateSubphaseRequestDto.ts';

export interface TemplatePhaseRequestDto {
  id?: string;
  /** @minLength 1 */
  name: string;
  order: number;
  description?: string;
  /** @minItems 1 */
  subphases: TemplateSubphaseRequestDto[];
}
