/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TemplateSummaryResponseDto {
  id?: string;
  name?: string;
  description?: string;
  type?: string;
  status?: string;
  phaseCount?: number;
  subphaseCount?: number;
}
