/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TemplateSubphaseResponseDto {
  id?: string;
  name?: string;
  order?: number;
  referenceUrl?: string;
  description?: string;
  requirements?: string;
}
