/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TemplateSubphaseResponseDto } from './templateSubphaseResponseDto.ts';

export interface TemplatePhaseResponseDto {
  id?: string;
  name?: string;
  order?: number;
  description?: string;
  subphases?: TemplateSubphaseResponseDto[];
}
