/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Respuesta de carga de evidencia v1 (FSD-UC-004)
 */
export interface UploadEvidenceResponse {
  /** Identificador de la evidencia */
  evidenceId: string;
  /** Versión creada (v1) */
  version: number;
  /** SHA-256 del contenido */
  contentHash: string;
  /** Evento de dominio publicado */
  event?: string;
  /** Estado vigente del indicador */
  currentState: string;
}
