/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UploadEvidenceResponse {
  evidenceId?: string;
  version?: number;
  contentHash?: string;
  event?: string;
  currentState?: string;
}
