/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UploadableIndicatorResponse {
  indicatorId?: string;
  code?: string;
  title?: string;
  criterionId?: string;
  criterionCode?: string;
  criterionTitle?: string;
  currentState?: string;
}
