/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Parts multipart de carga de evidencia
 */
export interface UploadEvidenceMultipartRequest {
  file: Blob;
  criterionId: string;
  description: string;
}
