/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UpsertTemplateRequestDto {
  /** @minLength 1 */
  name: string;
  description?: string;
  /** @minLength 1 */
  type: string;
}
