/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AssistantStatusResponse,
  SendChatMessageRequest,
  SendChatMessageResponse
} from '../../model';

import { customFetch } from '../../../lib/api/customFetch.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type chatResponse200 = {
  data: SendChatMessageResponse
  status: 200
}

export type chatResponseSuccess = (chatResponse200) & {
  headers: Headers;
};
;

export type chatResponse = (chatResponseSuccess)

export const getChatUrl = () => {




  return `/api/v1/assistant/chat`
}

/**
 * Proxy hacia Open WebUI (API compatible OpenAI).
 * @summary Enviar mensaje al asistente
 */
export const chat = async (sendChatMessageRequest: SendChatMessageRequest, options?: Parameters<typeof customFetch>[1]): Promise<chatResponse> => {

  return customFetch<chatResponse>(getChatUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(sendChatMessageRequest)
  }
);}





export const getChatMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof chat>>, TError,{data: SendChatMessageRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof chat>>, TError,{data: SendChatMessageRequest}, TContext> => {

const mutationKey = ['chat'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof chat>>, {data: SendChatMessageRequest}> = (props) => {
          const {data} = props ?? {};

          return  chat(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ChatMutationResult = NonNullable<Awaited<ReturnType<typeof chat>>>
    export type ChatMutationBody = SendChatMessageRequest
    export type ChatMutationError = unknown

    /**
 * @summary Enviar mensaje al asistente
 */
export const useChat = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof chat>>, TError,{data: SendChatMessageRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof chat>>,
        TError,
        {data: SendChatMessageRequest},
        TContext
      > => {
      return useMutation(getChatMutationOptions(options), queryClient);
    }
    export type getStatus1Response200 = {
  data: AssistantStatusResponse
  status: 200
}

export type getStatus1ResponseSuccess = (getStatus1Response200) & {
  headers: Headers;
};
;

export type getStatus1Response = (getStatus1ResponseSuccess)

export const getGetStatus1Url = () => {




  return `/api/v1/assistant/status`
}

/**
 * Indica si el asistente está habilitado y qué modelo usa.
 * @summary Estado del asistente
 */
export const getStatus1 = async ( options?: Parameters<typeof customFetch>[1]): Promise<getStatus1Response> => {

  return customFetch<getStatus1Response>(getGetStatus1Url(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetStatus1QueryKey = () => {
    return [
    `/api/v1/assistant/status`
    ] as const;
    }


export const getGetStatus1QueryOptions = <TData = Awaited<ReturnType<typeof getStatus1>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatus1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStatus1QueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStatus1>>> = ({ signal }) => getStatus1({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStatus1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStatus1QueryResult = NonNullable<Awaited<ReturnType<typeof getStatus1>>>
export type GetStatus1QueryError = unknown


export function useGetStatus1<TData = Awaited<ReturnType<typeof getStatus1>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatus1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatus1>>,
          TError,
          Awaited<ReturnType<typeof getStatus1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatus1<TData = Awaited<ReturnType<typeof getStatus1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatus1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatus1>>,
          TError,
          Awaited<ReturnType<typeof getStatus1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatus1<TData = Awaited<ReturnType<typeof getStatus1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatus1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Estado del asistente
 */

export function useGetStatus1<TData = Awaited<ReturnType<typeof getStatus1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatus1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStatus1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






