/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CompositeDashboardSummary,
  ExportJobRequest,
  ExportJobResponse,
  GetCoordinatorDetailsParams,
  JobStatusResponse,
  PageObservationSummary
} from '../../model';

import { customFetch } from '../../../lib/api/customFetch.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type enqueueExportJobResponse200 = {
  data: ExportJobResponse
  status: 200
}

export type enqueueExportJobResponseSuccess = (enqueueExportJobResponse200) & {
  headers: Headers;
};
;

export type enqueueExportJobResponse = (enqueueExportJobResponseSuccess)

export const getEnqueueExportJobUrl = () => {




  return `/api/v1/dashboards/export-jobs`
}

export const enqueueExportJob = async (exportJobRequest: ExportJobRequest, options?: Parameters<typeof customFetch>[1]): Promise<enqueueExportJobResponse> => {

  return customFetch<enqueueExportJobResponse>(getEnqueueExportJobUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(exportJobRequest)
  }
);}





export const getEnqueueExportJobMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof enqueueExportJob>>, TError,{data: ExportJobRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof enqueueExportJob>>, TError,{data: ExportJobRequest}, TContext> => {

const mutationKey = ['enqueueExportJob'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof enqueueExportJob>>, {data: ExportJobRequest}> = (props) => {
          const {data} = props ?? {};

          return  enqueueExportJob(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EnqueueExportJobMutationResult = NonNullable<Awaited<ReturnType<typeof enqueueExportJob>>>
    export type EnqueueExportJobMutationBody = ExportJobRequest
    export type EnqueueExportJobMutationError = unknown

    export const useEnqueueExportJob = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof enqueueExportJob>>, TError,{data: ExportJobRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof enqueueExportJob>>,
        TError,
        {data: ExportJobRequest},
        TContext
      > => {
      return useMutation(getEnqueueExportJobMutationOptions(options), queryClient);
    }
    export type enqueueExportJob1Response200 = {
  data: ExportJobResponse
  status: 200
}

export type enqueueExportJob1ResponseSuccess = (enqueueExportJob1Response200) & {
  headers: Headers;
};
;

export type enqueueExportJob1Response = (enqueueExportJob1ResponseSuccess)

export const getEnqueueExportJob1Url = () => {




  return `/api/v1/dashboards/coordinator/export-jobs`
}

export const enqueueExportJob1 = async (exportJobRequest: ExportJobRequest, options?: Parameters<typeof customFetch>[1]): Promise<enqueueExportJob1Response> => {

  return customFetch<enqueueExportJob1Response>(getEnqueueExportJob1Url(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(exportJobRequest)
  }
);}





export const getEnqueueExportJob1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof enqueueExportJob1>>, TError,{data: ExportJobRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof enqueueExportJob1>>, TError,{data: ExportJobRequest}, TContext> => {

const mutationKey = ['enqueueExportJob1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof enqueueExportJob1>>, {data: ExportJobRequest}> = (props) => {
          const {data} = props ?? {};

          return  enqueueExportJob1(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EnqueueExportJob1MutationResult = NonNullable<Awaited<ReturnType<typeof enqueueExportJob1>>>
    export type EnqueueExportJob1MutationBody = ExportJobRequest
    export type EnqueueExportJob1MutationError = unknown

    export const useEnqueueExportJob1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof enqueueExportJob1>>, TError,{data: ExportJobRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof enqueueExportJob1>>,
        TError,
        {data: ExportJobRequest},
        TContext
      > => {
      return useMutation(getEnqueueExportJob1MutationOptions(options), queryClient);
    }
    export type getCompositeSummaryResponse200 = {
  data: CompositeDashboardSummary
  status: 200
}

export type getCompositeSummaryResponseSuccess = (getCompositeSummaryResponse200) & {
  headers: Headers;
};
;

export type getCompositeSummaryResponse = (getCompositeSummaryResponseSuccess)

export const getGetCompositeSummaryUrl = () => {




  return `/api/v1/dashboards/me/summary`
}

export const getCompositeSummary = async ( options?: Parameters<typeof customFetch>[1]): Promise<getCompositeSummaryResponse> => {

  return customFetch<getCompositeSummaryResponse>(getGetCompositeSummaryUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCompositeSummaryQueryKey = () => {
    return [
    `/api/v1/dashboards/me/summary`
    ] as const;
    }


export const getGetCompositeSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getCompositeSummary>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompositeSummary>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCompositeSummaryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCompositeSummary>>> = ({ signal }) => getCompositeSummary({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCompositeSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCompositeSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getCompositeSummary>>>
export type GetCompositeSummaryQueryError = unknown


export function useGetCompositeSummary<TData = Awaited<ReturnType<typeof getCompositeSummary>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompositeSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompositeSummary>>,
          TError,
          Awaited<ReturnType<typeof getCompositeSummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCompositeSummary<TData = Awaited<ReturnType<typeof getCompositeSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompositeSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompositeSummary>>,
          TError,
          Awaited<ReturnType<typeof getCompositeSummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCompositeSummary<TData = Awaited<ReturnType<typeof getCompositeSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompositeSummary>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCompositeSummary<TData = Awaited<ReturnType<typeof getCompositeSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompositeSummary>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCompositeSummaryQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getJobStatusResponse200 = {
  data: JobStatusResponse
  status: 200
}

export type getJobStatusResponseSuccess = (getJobStatusResponse200) & {
  headers: Headers;
};
;

export type getJobStatusResponse = (getJobStatusResponseSuccess)

export const getGetJobStatusUrl = (jobId: string,) => {




  return `/api/v1/dashboards/export-jobs/${jobId}`
}

export const getJobStatus = async (jobId: string, options?: Parameters<typeof customFetch>[1]): Promise<getJobStatusResponse> => {

  return customFetch<getJobStatusResponse>(getGetJobStatusUrl(jobId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetJobStatusQueryKey = (jobId: string,) => {
    return [
    `/api/v1/dashboards/export-jobs/${jobId}`
    ] as const;
    }


export const getGetJobStatusQueryOptions = <TData = Awaited<ReturnType<typeof getJobStatus>>, TError = unknown>(jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobStatus>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetJobStatusQueryKey(jobId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getJobStatus>>> = ({ signal }) => getJobStatus(jobId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: jobId !== null && jobId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getJobStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetJobStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getJobStatus>>>
export type GetJobStatusQueryError = unknown


export function useGetJobStatus<TData = Awaited<ReturnType<typeof getJobStatus>>, TError = unknown>(
 jobId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJobStatus>>,
          TError,
          Awaited<ReturnType<typeof getJobStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetJobStatus<TData = Awaited<ReturnType<typeof getJobStatus>>, TError = unknown>(
 jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJobStatus>>,
          TError,
          Awaited<ReturnType<typeof getJobStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetJobStatus<TData = Awaited<ReturnType<typeof getJobStatus>>, TError = unknown>(
 jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobStatus>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetJobStatus<TData = Awaited<ReturnType<typeof getJobStatus>>, TError = unknown>(
 jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobStatus>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetJobStatusQueryOptions(jobId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type downloadReportResponse200 = {
  data: Blob
  status: 200
}

export type downloadReportResponseSuccess = (downloadReportResponse200) & {
  headers: Headers;
};
;

export type downloadReportResponse = (downloadReportResponseSuccess)

export const getDownloadReportUrl = (jobId: string,) => {




  return `/api/v1/dashboards/export-jobs/${jobId}/download`
}

export const downloadReport = async (jobId: string, options?: Parameters<typeof customFetch>[1]): Promise<downloadReportResponse> => {

  return customFetch<downloadReportResponse>(getDownloadReportUrl(jobId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getDownloadReportQueryKey = (jobId: string,) => {
    return [
    `/api/v1/dashboards/export-jobs/${jobId}/download`
    ] as const;
    }


export const getDownloadReportQueryOptions = <TData = Awaited<ReturnType<typeof downloadReport>>, TError = unknown>(jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadReport>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadReportQueryKey(jobId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadReport>>> = ({ signal }) => downloadReport(jobId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: jobId !== null && jobId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadReportQueryResult = NonNullable<Awaited<ReturnType<typeof downloadReport>>>
export type DownloadReportQueryError = unknown


export function useDownloadReport<TData = Awaited<ReturnType<typeof downloadReport>>, TError = unknown>(
 jobId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadReport>>,
          TError,
          Awaited<ReturnType<typeof downloadReport>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadReport<TData = Awaited<ReturnType<typeof downloadReport>>, TError = unknown>(
 jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadReport>>,
          TError,
          Awaited<ReturnType<typeof downloadReport>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadReport<TData = Awaited<ReturnType<typeof downloadReport>>, TError = unknown>(
 jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadReport>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDownloadReport<TData = Awaited<ReturnType<typeof downloadReport>>, TError = unknown>(
 jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadReport>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownloadReportQueryOptions(jobId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getCoordinatorDetailsResponse200 = {
  data: PageObservationSummary
  status: 200
}

export type getCoordinatorDetailsResponseSuccess = (getCoordinatorDetailsResponse200) & {
  headers: Headers;
};
;

export type getCoordinatorDetailsResponse = (getCoordinatorDetailsResponseSuccess)

export const getGetCoordinatorDetailsUrl = (params: GetCoordinatorDetailsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/dashboards/coordinator/details?${stringifiedParams}` : `/api/v1/dashboards/coordinator/details`
}

export const getCoordinatorDetails = async (params: GetCoordinatorDetailsParams, options?: Parameters<typeof customFetch>[1]): Promise<getCoordinatorDetailsResponse> => {

  return customFetch<getCoordinatorDetailsResponse>(getGetCoordinatorDetailsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCoordinatorDetailsQueryKey = (params?: GetCoordinatorDetailsParams,) => {
    return [
    `/api/v1/dashboards/coordinator/details`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetCoordinatorDetailsQueryOptions = <TData = Awaited<ReturnType<typeof getCoordinatorDetails>>, TError = unknown>(params: GetCoordinatorDetailsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCoordinatorDetails>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCoordinatorDetailsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCoordinatorDetails>>> = ({ signal }) => getCoordinatorDetails(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCoordinatorDetails>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCoordinatorDetailsQueryResult = NonNullable<Awaited<ReturnType<typeof getCoordinatorDetails>>>
export type GetCoordinatorDetailsQueryError = unknown


export function useGetCoordinatorDetails<TData = Awaited<ReturnType<typeof getCoordinatorDetails>>, TError = unknown>(
 params: GetCoordinatorDetailsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCoordinatorDetails>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoordinatorDetails>>,
          TError,
          Awaited<ReturnType<typeof getCoordinatorDetails>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCoordinatorDetails<TData = Awaited<ReturnType<typeof getCoordinatorDetails>>, TError = unknown>(
 params: GetCoordinatorDetailsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCoordinatorDetails>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoordinatorDetails>>,
          TError,
          Awaited<ReturnType<typeof getCoordinatorDetails>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCoordinatorDetails<TData = Awaited<ReturnType<typeof getCoordinatorDetails>>, TError = unknown>(
 params: GetCoordinatorDetailsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCoordinatorDetails>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCoordinatorDetails<TData = Awaited<ReturnType<typeof getCoordinatorDetails>>, TError = unknown>(
 params: GetCoordinatorDetailsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCoordinatorDetails>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCoordinatorDetailsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






