/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  CreatePhaseRequestDto,
  CreateSubphaseRequestDto,
  PhaseDto,
  ProcessResponseDto,
  ReorderStructureRequestDto,
  SubphaseDto,
  UpdatePhaseRequestDto,
  UpdateSubphaseRequestDto
} from '../../model';

import { customFetch } from '../../../lib/api/customFetch.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type reorderStructureResponse200 = {
  data: ProcessResponseDto
  status: 200
}

export type reorderStructureResponseSuccess = (reorderStructureResponse200) & {
  headers: Headers;
};
;

export type reorderStructureResponse = (reorderStructureResponseSuccess)

export const getReorderStructureUrl = (processId: string,) => {




  return `/api/v1/processes/${processId}/structure/reorder`
}

/**
 * @summary Reordenar fases y/o subfases
 */
export const reorderStructure = async (processId: string,
    reorderStructureRequestDto: ReorderStructureRequestDto, options?: Parameters<typeof customFetch>[1]): Promise<reorderStructureResponse> => {

  return customFetch<reorderStructureResponse>(getReorderStructureUrl(processId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(reorderStructureRequestDto)
  }
);}





export const getReorderStructureMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reorderStructure>>, TError,{processId: string;data: ReorderStructureRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof reorderStructure>>, TError,{processId: string;data: ReorderStructureRequestDto}, TContext> => {

const mutationKey = ['reorderStructure'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reorderStructure>>, {processId: string;data: ReorderStructureRequestDto}> = (props) => {
          const {processId,data} = props ?? {};

          return  reorderStructure(processId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReorderStructureMutationResult = NonNullable<Awaited<ReturnType<typeof reorderStructure>>>
    export type ReorderStructureMutationBody = ReorderStructureRequestDto
    export type ReorderStructureMutationError = unknown

    /**
 * @summary Reordenar fases y/o subfases
 */
export const useReorderStructure = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reorderStructure>>, TError,{processId: string;data: ReorderStructureRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reorderStructure>>,
        TError,
        {processId: string;data: ReorderStructureRequestDto},
        TContext
      > => {
      return useMutation(getReorderStructureMutationOptions(options), queryClient);
    }
    export type updatePhaseResponse200 = {
  data: PhaseDto
  status: 200
}

export type updatePhaseResponseSuccess = (updatePhaseResponse200) & {
  headers: Headers;
};
;

export type updatePhaseResponse = (updatePhaseResponseSuccess)

export const getUpdatePhaseUrl = (processId: string,
    phaseId: string,) => {




  return `/api/v1/processes/${processId}/phases/${phaseId}`
}

/**
 * @summary Actualizar fase de proceso
 */
export const updatePhase = async (processId: string,
    phaseId: string,
    updatePhaseRequestDto: UpdatePhaseRequestDto, options?: Parameters<typeof customFetch>[1]): Promise<updatePhaseResponse> => {

  return customFetch<updatePhaseResponse>(getUpdatePhaseUrl(processId,phaseId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updatePhaseRequestDto)
  }
);}





export const getUpdatePhaseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePhase>>, TError,{processId: string;phaseId: string;data: UpdatePhaseRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePhase>>, TError,{processId: string;phaseId: string;data: UpdatePhaseRequestDto}, TContext> => {

const mutationKey = ['updatePhase'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePhase>>, {processId: string;phaseId: string;data: UpdatePhaseRequestDto}> = (props) => {
          const {processId,phaseId,data} = props ?? {};

          return  updatePhase(processId,phaseId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdatePhaseMutationResult = NonNullable<Awaited<ReturnType<typeof updatePhase>>>
    export type UpdatePhaseMutationBody = UpdatePhaseRequestDto
    export type UpdatePhaseMutationError = unknown

    /**
 * @summary Actualizar fase de proceso
 */
export const useUpdatePhase = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePhase>>, TError,{processId: string;phaseId: string;data: UpdatePhaseRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePhase>>,
        TError,
        {processId: string;phaseId: string;data: UpdatePhaseRequestDto},
        TContext
      > => {
      return useMutation(getUpdatePhaseMutationOptions(options), queryClient);
    }
    export type deletePhaseResponse200 = {
  data: void
  status: 200
}

export type deletePhaseResponseSuccess = (deletePhaseResponse200) & {
  headers: Headers;
};
;

export type deletePhaseResponse = (deletePhaseResponseSuccess)

export const getDeletePhaseUrl = (processId: string,
    phaseId: string,) => {




  return `/api/v1/processes/${processId}/phases/${phaseId}`
}

/**
 * @summary Eliminar fase de proceso
 */
export const deletePhase = async (processId: string,
    phaseId: string, options?: Parameters<typeof customFetch>[1]): Promise<deletePhaseResponse> => {

  return customFetch<deletePhaseResponse>(getDeletePhaseUrl(processId,phaseId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeletePhaseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePhase>>, TError,{processId: string;phaseId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePhase>>, TError,{processId: string;phaseId: string}, TContext> => {

const mutationKey = ['deletePhase'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePhase>>, {processId: string;phaseId: string}> = (props) => {
          const {processId,phaseId} = props ?? {};

          return  deletePhase(processId,phaseId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeletePhaseMutationResult = NonNullable<Awaited<ReturnType<typeof deletePhase>>>

    export type DeletePhaseMutationError = unknown

    /**
 * @summary Eliminar fase de proceso
 */
export const useDeletePhase = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePhase>>, TError,{processId: string;phaseId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePhase>>,
        TError,
        {processId: string;phaseId: string},
        TContext
      > => {
      return useMutation(getDeletePhaseMutationOptions(options), queryClient);
    }
    export type updateSubphaseResponse200 = {
  data: SubphaseDto
  status: 200
}

export type updateSubphaseResponseSuccess = (updateSubphaseResponse200) & {
  headers: Headers;
};
;

export type updateSubphaseResponse = (updateSubphaseResponseSuccess)

export const getUpdateSubphaseUrl = (processId: string,
    phaseId: string,
    subphaseId: string,) => {




  return `/api/v1/processes/${processId}/phases/${phaseId}/subphases/${subphaseId}`
}

/**
 * @summary Actualizar subfase
 */
export const updateSubphase = async (processId: string,
    phaseId: string,
    subphaseId: string,
    updateSubphaseRequestDto: UpdateSubphaseRequestDto, options?: Parameters<typeof customFetch>[1]): Promise<updateSubphaseResponse> => {

  return customFetch<updateSubphaseResponse>(getUpdateSubphaseUrl(processId,phaseId,subphaseId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateSubphaseRequestDto)
  }
);}





export const getUpdateSubphaseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSubphase>>, TError,{processId: string;phaseId: string;subphaseId: string;data: UpdateSubphaseRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateSubphase>>, TError,{processId: string;phaseId: string;subphaseId: string;data: UpdateSubphaseRequestDto}, TContext> => {

const mutationKey = ['updateSubphase'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSubphase>>, {processId: string;phaseId: string;subphaseId: string;data: UpdateSubphaseRequestDto}> = (props) => {
          const {processId,phaseId,subphaseId,data} = props ?? {};

          return  updateSubphase(processId,phaseId,subphaseId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateSubphaseMutationResult = NonNullable<Awaited<ReturnType<typeof updateSubphase>>>
    export type UpdateSubphaseMutationBody = UpdateSubphaseRequestDto
    export type UpdateSubphaseMutationError = unknown

    /**
 * @summary Actualizar subfase
 */
export const useUpdateSubphase = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSubphase>>, TError,{processId: string;phaseId: string;subphaseId: string;data: UpdateSubphaseRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSubphase>>,
        TError,
        {processId: string;phaseId: string;subphaseId: string;data: UpdateSubphaseRequestDto},
        TContext
      > => {
      return useMutation(getUpdateSubphaseMutationOptions(options), queryClient);
    }
    export type deleteSubphaseResponse200 = {
  data: void
  status: 200
}

export type deleteSubphaseResponseSuccess = (deleteSubphaseResponse200) & {
  headers: Headers;
};
;

export type deleteSubphaseResponse = (deleteSubphaseResponseSuccess)

export const getDeleteSubphaseUrl = (processId: string,
    phaseId: string,
    subphaseId: string,) => {




  return `/api/v1/processes/${processId}/phases/${phaseId}/subphases/${subphaseId}`
}

/**
 * @summary Eliminar subfase
 */
export const deleteSubphase = async (processId: string,
    phaseId: string,
    subphaseId: string, options?: Parameters<typeof customFetch>[1]): Promise<deleteSubphaseResponse> => {

  return customFetch<deleteSubphaseResponse>(getDeleteSubphaseUrl(processId,phaseId,subphaseId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteSubphaseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSubphase>>, TError,{processId: string;phaseId: string;subphaseId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSubphase>>, TError,{processId: string;phaseId: string;subphaseId: string}, TContext> => {

const mutationKey = ['deleteSubphase'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSubphase>>, {processId: string;phaseId: string;subphaseId: string}> = (props) => {
          const {processId,phaseId,subphaseId} = props ?? {};

          return  deleteSubphase(processId,phaseId,subphaseId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteSubphaseMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSubphase>>>

    export type DeleteSubphaseMutationError = unknown

    /**
 * @summary Eliminar subfase
 */
export const useDeleteSubphase = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSubphase>>, TError,{processId: string;phaseId: string;subphaseId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSubphase>>,
        TError,
        {processId: string;phaseId: string;subphaseId: string},
        TContext
      > => {
      return useMutation(getDeleteSubphaseMutationOptions(options), queryClient);
    }
    export type addPhaseResponse200 = {
  data: PhaseDto
  status: 200
}

export type addPhaseResponseSuccess = (addPhaseResponse200) & {
  headers: Headers;
};
;

export type addPhaseResponse = (addPhaseResponseSuccess)

export const getAddPhaseUrl = (processId: string,) => {




  return `/api/v1/processes/${processId}/phases`
}

/**
 * @summary Agregar fase a proceso ACTIVE
 */
export const addPhase = async (processId: string,
    createPhaseRequestDto: CreatePhaseRequestDto, options?: Parameters<typeof customFetch>[1]): Promise<addPhaseResponse> => {

  return customFetch<addPhaseResponse>(getAddPhaseUrl(processId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createPhaseRequestDto)
  }
);}





export const getAddPhaseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addPhase>>, TError,{processId: string;data: CreatePhaseRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof addPhase>>, TError,{processId: string;data: CreatePhaseRequestDto}, TContext> => {

const mutationKey = ['addPhase'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addPhase>>, {processId: string;data: CreatePhaseRequestDto}> = (props) => {
          const {processId,data} = props ?? {};

          return  addPhase(processId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddPhaseMutationResult = NonNullable<Awaited<ReturnType<typeof addPhase>>>
    export type AddPhaseMutationBody = CreatePhaseRequestDto
    export type AddPhaseMutationError = unknown

    /**
 * @summary Agregar fase a proceso ACTIVE
 */
export const useAddPhase = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addPhase>>, TError,{processId: string;data: CreatePhaseRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addPhase>>,
        TError,
        {processId: string;data: CreatePhaseRequestDto},
        TContext
      > => {
      return useMutation(getAddPhaseMutationOptions(options), queryClient);
    }
    export type addSubphaseResponse200 = {
  data: SubphaseDto
  status: 200
}

export type addSubphaseResponseSuccess = (addSubphaseResponse200) & {
  headers: Headers;
};
;

export type addSubphaseResponse = (addSubphaseResponseSuccess)

export const getAddSubphaseUrl = (processId: string,
    phaseId: string,) => {




  return `/api/v1/processes/${processId}/phases/${phaseId}/subphases`
}

/**
 * @summary Agregar subfase a fase
 */
export const addSubphase = async (processId: string,
    phaseId: string,
    createSubphaseRequestDto: CreateSubphaseRequestDto, options?: Parameters<typeof customFetch>[1]): Promise<addSubphaseResponse> => {

  return customFetch<addSubphaseResponse>(getAddSubphaseUrl(processId,phaseId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createSubphaseRequestDto)
  }
);}





export const getAddSubphaseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addSubphase>>, TError,{processId: string;phaseId: string;data: CreateSubphaseRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof addSubphase>>, TError,{processId: string;phaseId: string;data: CreateSubphaseRequestDto}, TContext> => {

const mutationKey = ['addSubphase'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addSubphase>>, {processId: string;phaseId: string;data: CreateSubphaseRequestDto}> = (props) => {
          const {processId,phaseId,data} = props ?? {};

          return  addSubphase(processId,phaseId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddSubphaseMutationResult = NonNullable<Awaited<ReturnType<typeof addSubphase>>>
    export type AddSubphaseMutationBody = CreateSubphaseRequestDto
    export type AddSubphaseMutationError = unknown

    /**
 * @summary Agregar subfase a fase
 */
export const useAddSubphase = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addSubphase>>, TError,{processId: string;phaseId: string;data: CreateSubphaseRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addSubphase>>,
        TError,
        {processId: string;phaseId: string;data: CreateSubphaseRequestDto},
        TContext
      > => {
      return useMutation(getAddSubphaseMutationOptions(options), queryClient);
    }
