/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateSubphaseObservationRequestDto,
  RejectIndicatorRequestDto,
  SubphaseApproveResponseDto,
  SubphaseEvidenceResponseDto,
  SubphaseObservationResponseDto,
  SubphaseRejectResponseDto,
  SubphaseSubsanationEligibilityResponseDto,
  SubsanateEvidenceBody,
  SubsanateSubphaseEvidenceResponseDto,
  UploadEvidenceBody,
  UploadEvidenceResponse
} from '../../model';

import { customFetch } from '../../../lib/api/customFetch.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type rejectSubphaseResponse200 = {
  data: SubphaseRejectResponseDto
  status: 200
}

export type rejectSubphaseResponseSuccess = (rejectSubphaseResponse200) & {
  headers: Headers;
};
;

export type rejectSubphaseResponse = (rejectSubphaseResponseSuccess)

export const getRejectSubphaseUrl = (subphaseId: string,) => {




  return `/api/v1/subphases/${subphaseId}/reject`
}

/**
 * @summary Rechazar subfase (requiere evidencia)
 */
export const rejectSubphase = async (subphaseId: string,
    rejectIndicatorRequestDto: RejectIndicatorRequestDto, options?: Parameters<typeof customFetch>[1]): Promise<rejectSubphaseResponse> => {

  return customFetch<rejectSubphaseResponse>(getRejectSubphaseUrl(subphaseId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(rejectIndicatorRequestDto)
  }
);}





export const getRejectSubphaseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectSubphase>>, TError,{subphaseId: string;data: RejectIndicatorRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof rejectSubphase>>, TError,{subphaseId: string;data: RejectIndicatorRequestDto}, TContext> => {

const mutationKey = ['rejectSubphase'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rejectSubphase>>, {subphaseId: string;data: RejectIndicatorRequestDto}> = (props) => {
          const {subphaseId,data} = props ?? {};

          return  rejectSubphase(subphaseId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RejectSubphaseMutationResult = NonNullable<Awaited<ReturnType<typeof rejectSubphase>>>
    export type RejectSubphaseMutationBody = RejectIndicatorRequestDto
    export type RejectSubphaseMutationError = unknown

    /**
 * @summary Rechazar subfase (requiere evidencia)
 */
export const useRejectSubphase = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectSubphase>>, TError,{subphaseId: string;data: RejectIndicatorRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof rejectSubphase>>,
        TError,
        {subphaseId: string;data: RejectIndicatorRequestDto},
        TContext
      > => {
      return useMutation(getRejectSubphaseMutationOptions(options), queryClient);
    }
    export type listObservationsResponse200 = {
  data: SubphaseObservationResponseDto[]
  status: 200
}

export type listObservationsResponseSuccess = (listObservationsResponse200) & {
  headers: Headers;
};
;

export type listObservationsResponse = (listObservationsResponseSuccess)

export const getListObservationsUrl = (subphaseId: string,) => {




  return `/api/v1/subphases/${subphaseId}/observations`
}

/**
 * @summary Listar observaciones de la subfase
 */
export const listObservations = async (subphaseId: string, options?: Parameters<typeof customFetch>[1]): Promise<listObservationsResponse> => {

  return customFetch<listObservationsResponse>(getListObservationsUrl(subphaseId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListObservationsQueryKey = (subphaseId: string,) => {
    return [
    `/api/v1/subphases/${subphaseId}/observations`
    ] as const;
    }


export const getListObservationsQueryOptions = <TData = Awaited<ReturnType<typeof listObservations>>, TError = unknown>(subphaseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listObservations>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListObservationsQueryKey(subphaseId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listObservations>>> = ({ signal }) => listObservations(subphaseId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: subphaseId !== null && subphaseId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listObservations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListObservationsQueryResult = NonNullable<Awaited<ReturnType<typeof listObservations>>>
export type ListObservationsQueryError = unknown


export function useListObservations<TData = Awaited<ReturnType<typeof listObservations>>, TError = unknown>(
 subphaseId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listObservations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listObservations>>,
          TError,
          Awaited<ReturnType<typeof listObservations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListObservations<TData = Awaited<ReturnType<typeof listObservations>>, TError = unknown>(
 subphaseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listObservations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listObservations>>,
          TError,
          Awaited<ReturnType<typeof listObservations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListObservations<TData = Awaited<ReturnType<typeof listObservations>>, TError = unknown>(
 subphaseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listObservations>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar observaciones de la subfase
 */

export function useListObservations<TData = Awaited<ReturnType<typeof listObservations>>, TError = unknown>(
 subphaseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listObservations>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListObservationsQueryOptions(subphaseId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type addObservationResponse200 = {
  data: SubphaseObservationResponseDto
  status: 200
}

export type addObservationResponseSuccess = (addObservationResponse200) & {
  headers: Headers;
};
;

export type addObservationResponse = (addObservationResponseSuccess)

export const getAddObservationUrl = (subphaseId: string,) => {




  return `/api/v1/subphases/${subphaseId}/observations`
}

/**
 * @summary Registrar observación sobre evidencias de la subfase
 */
export const addObservation = async (subphaseId: string,
    createSubphaseObservationRequestDto: CreateSubphaseObservationRequestDto, options?: Parameters<typeof customFetch>[1]): Promise<addObservationResponse> => {

  return customFetch<addObservationResponse>(getAddObservationUrl(subphaseId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createSubphaseObservationRequestDto)
  }
);}





export const getAddObservationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addObservation>>, TError,{subphaseId: string;data: CreateSubphaseObservationRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof addObservation>>, TError,{subphaseId: string;data: CreateSubphaseObservationRequestDto}, TContext> => {

const mutationKey = ['addObservation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addObservation>>, {subphaseId: string;data: CreateSubphaseObservationRequestDto}> = (props) => {
          const {subphaseId,data} = props ?? {};

          return  addObservation(subphaseId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddObservationMutationResult = NonNullable<Awaited<ReturnType<typeof addObservation>>>
    export type AddObservationMutationBody = CreateSubphaseObservationRequestDto
    export type AddObservationMutationError = unknown

    /**
 * @summary Registrar observación sobre evidencias de la subfase
 */
export const useAddObservation = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addObservation>>, TError,{subphaseId: string;data: CreateSubphaseObservationRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addObservation>>,
        TError,
        {subphaseId: string;data: CreateSubphaseObservationRequestDto},
        TContext
      > => {
      return useMutation(getAddObservationMutationOptions(options), queryClient);
    }
    export type listEvidencesResponse200 = {
  data: SubphaseEvidenceResponseDto[]
  status: 200
}

export type listEvidencesResponseSuccess = (listEvidencesResponse200) & {
  headers: Headers;
};
;

export type listEvidencesResponse = (listEvidencesResponseSuccess)

export const getListEvidencesUrl = (subphaseId: string,) => {




  return `/api/v1/subphases/${subphaseId}/evidences`
}

/**
 * @summary Listar evidencias cargadas en la subfase
 */
export const listEvidences = async (subphaseId: string, options?: Parameters<typeof customFetch>[1]): Promise<listEvidencesResponse> => {

  return customFetch<listEvidencesResponse>(getListEvidencesUrl(subphaseId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListEvidencesQueryKey = (subphaseId: string,) => {
    return [
    `/api/v1/subphases/${subphaseId}/evidences`
    ] as const;
    }


export const getListEvidencesQueryOptions = <TData = Awaited<ReturnType<typeof listEvidences>>, TError = unknown>(subphaseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEvidences>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListEvidencesQueryKey(subphaseId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listEvidences>>> = ({ signal }) => listEvidences(subphaseId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: subphaseId !== null && subphaseId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listEvidences>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListEvidencesQueryResult = NonNullable<Awaited<ReturnType<typeof listEvidences>>>
export type ListEvidencesQueryError = unknown


export function useListEvidences<TData = Awaited<ReturnType<typeof listEvidences>>, TError = unknown>(
 subphaseId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEvidences>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEvidences>>,
          TError,
          Awaited<ReturnType<typeof listEvidences>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEvidences<TData = Awaited<ReturnType<typeof listEvidences>>, TError = unknown>(
 subphaseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEvidences>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEvidences>>,
          TError,
          Awaited<ReturnType<typeof listEvidences>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEvidences<TData = Awaited<ReturnType<typeof listEvidences>>, TError = unknown>(
 subphaseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEvidences>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar evidencias cargadas en la subfase
 */

export function useListEvidences<TData = Awaited<ReturnType<typeof listEvidences>>, TError = unknown>(
 subphaseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEvidences>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListEvidencesQueryOptions(subphaseId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type uploadEvidenceResponse200 = {
  data: UploadEvidenceResponse
  status: 200
}

export type uploadEvidenceResponseSuccess = (uploadEvidenceResponse200) & {
  headers: Headers;
};
;

export type uploadEvidenceResponse = (uploadEvidenceResponseSuccess)

export const getUploadEvidenceUrl = (subphaseId: string,) => {




  return `/api/v1/subphases/${subphaseId}/evidences`
}

/**
 * @summary Cargar evidencia en subfase (1..N por subfase)
 */
export const uploadEvidence = async (subphaseId: string,
    uploadEvidenceBody?: UploadEvidenceBody, options?: Parameters<typeof customFetch>[1]): Promise<uploadEvidenceResponse> => {
    const formData = new FormData();
if(uploadEvidenceBody?.file !== undefined) {
 formData.append(`file`, uploadEvidenceBody.file);
 }
if(uploadEvidenceBody?.description !== undefined) {
 formData.append(`description`, uploadEvidenceBody.description);
 }

  return customFetch<uploadEvidenceResponse>(getUploadEvidenceUrl(subphaseId),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}





export const getUploadEvidenceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadEvidence>>, TError,{subphaseId: string;data?: UploadEvidenceBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadEvidence>>, TError,{subphaseId: string;data?: UploadEvidenceBody}, TContext> => {

const mutationKey = ['uploadEvidence'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadEvidence>>, {subphaseId: string;data?: UploadEvidenceBody}> = (props) => {
          const {subphaseId,data} = props ?? {};

          return  uploadEvidence(subphaseId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UploadEvidenceMutationResult = NonNullable<Awaited<ReturnType<typeof uploadEvidence>>>
    export type UploadEvidenceMutationBody = UploadEvidenceBody | undefined
    export type UploadEvidenceMutationError = unknown

    /**
 * @summary Cargar evidencia en subfase (1..N por subfase)
 */
export const useUploadEvidence = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadEvidence>>, TError,{subphaseId: string;data?: UploadEvidenceBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadEvidence>>,
        TError,
        {subphaseId: string;data?: UploadEvidenceBody},
        TContext
      > => {
      return useMutation(getUploadEvidenceMutationOptions(options), queryClient);
    }
    export type subsanateEvidenceResponse200 = {
  data: SubsanateSubphaseEvidenceResponseDto
  status: 200
}

export type subsanateEvidenceResponseSuccess = (subsanateEvidenceResponse200) & {
  headers: Headers;
};
;

export type subsanateEvidenceResponse = (subsanateEvidenceResponseSuccess)

export const getSubsanateEvidenceUrl = (subphaseId: string,
    evidenceId: string,) => {




  return `/api/v1/subphases/${subphaseId}/evidences/${evidenceId}/subsanate`
}

/**
 * @summary Subsanar evidencia (una vez por observación OPEN)
 */
export const subsanateEvidence = async (subphaseId: string,
    evidenceId: string,
    subsanateEvidenceBody?: SubsanateEvidenceBody, options?: Parameters<typeof customFetch>[1]): Promise<subsanateEvidenceResponse> => {
    const formData = new FormData();
if(subsanateEvidenceBody?.file !== undefined) {
 formData.append(`file`, subsanateEvidenceBody.file);
 }
if(subsanateEvidenceBody?.description !== undefined) {
 formData.append(`description`, subsanateEvidenceBody.description);
 }
if(subsanateEvidenceBody?.observationId !== undefined) {
 formData.append(`observationId`, subsanateEvidenceBody.observationId);
 }

  return customFetch<subsanateEvidenceResponse>(getSubsanateEvidenceUrl(subphaseId,evidenceId),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}





export const getSubsanateEvidenceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subsanateEvidence>>, TError,{subphaseId: string;evidenceId: string;data?: SubsanateEvidenceBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof subsanateEvidence>>, TError,{subphaseId: string;evidenceId: string;data?: SubsanateEvidenceBody}, TContext> => {

const mutationKey = ['subsanateEvidence'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof subsanateEvidence>>, {subphaseId: string;evidenceId: string;data?: SubsanateEvidenceBody}> = (props) => {
          const {subphaseId,evidenceId,data} = props ?? {};

          return  subsanateEvidence(subphaseId,evidenceId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SubsanateEvidenceMutationResult = NonNullable<Awaited<ReturnType<typeof subsanateEvidence>>>
    export type SubsanateEvidenceMutationBody = SubsanateEvidenceBody | undefined
    export type SubsanateEvidenceMutationError = unknown

    /**
 * @summary Subsanar evidencia (una vez por observación OPEN)
 */
export const useSubsanateEvidence = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subsanateEvidence>>, TError,{subphaseId: string;evidenceId: string;data?: SubsanateEvidenceBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof subsanateEvidence>>,
        TError,
        {subphaseId: string;evidenceId: string;data?: SubsanateEvidenceBody},
        TContext
      > => {
      return useMutation(getSubsanateEvidenceMutationOptions(options), queryClient);
    }
    export type approveSubphaseResponse200 = {
  data: SubphaseApproveResponseDto
  status: 200
}

export type approveSubphaseResponseSuccess = (approveSubphaseResponse200) & {
  headers: Headers;
};
;

export type approveSubphaseResponse = (approveSubphaseResponseSuccess)

export const getApproveSubphaseUrl = (subphaseId: string,) => {




  return `/api/v1/subphases/${subphaseId}/approve`
}

/**
 * @summary Aprobar subfase (requiere evidencia)
 */
export const approveSubphase = async (subphaseId: string, options?: Parameters<typeof customFetch>[1]): Promise<approveSubphaseResponse> => {

  return customFetch<approveSubphaseResponse>(getApproveSubphaseUrl(subphaseId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getApproveSubphaseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approveSubphase>>, TError,{subphaseId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof approveSubphase>>, TError,{subphaseId: string}, TContext> => {

const mutationKey = ['approveSubphase'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof approveSubphase>>, {subphaseId: string}> = (props) => {
          const {subphaseId} = props ?? {};

          return  approveSubphase(subphaseId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ApproveSubphaseMutationResult = NonNullable<Awaited<ReturnType<typeof approveSubphase>>>

    export type ApproveSubphaseMutationError = unknown

    /**
 * @summary Aprobar subfase (requiere evidencia)
 */
export const useApproveSubphase = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approveSubphase>>, TError,{subphaseId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof approveSubphase>>,
        TError,
        {subphaseId: string},
        TContext
      > => {
      return useMutation(getApproveSubphaseMutationOptions(options), queryClient);
    }
    export type subsanationEligibilityResponse200 = {
  data: SubphaseSubsanationEligibilityResponseDto
  status: 200
}

export type subsanationEligibilityResponseSuccess = (subsanationEligibilityResponse200) & {
  headers: Headers;
};
;

export type subsanationEligibilityResponse = (subsanationEligibilityResponseSuccess)

export const getSubsanationEligibilityUrl = (subphaseId: string,) => {




  return `/api/v1/subphases/${subphaseId}/subsanation-eligibility`
}

/**
 * @summary Verificar si la subfase permite subsanación
 */
export const subsanationEligibility = async (subphaseId: string, options?: Parameters<typeof customFetch>[1]): Promise<subsanationEligibilityResponse> => {

  return customFetch<subsanationEligibilityResponse>(getSubsanationEligibilityUrl(subphaseId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getSubsanationEligibilityQueryKey = (subphaseId: string,) => {
    return [
    `/api/v1/subphases/${subphaseId}/subsanation-eligibility`
    ] as const;
    }


export const getSubsanationEligibilityQueryOptions = <TData = Awaited<ReturnType<typeof subsanationEligibility>>, TError = unknown>(subphaseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subsanationEligibility>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSubsanationEligibilityQueryKey(subphaseId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof subsanationEligibility>>> = ({ signal }) => subsanationEligibility(subphaseId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: subphaseId !== null && subphaseId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof subsanationEligibility>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SubsanationEligibilityQueryResult = NonNullable<Awaited<ReturnType<typeof subsanationEligibility>>>
export type SubsanationEligibilityQueryError = unknown


export function useSubsanationEligibility<TData = Awaited<ReturnType<typeof subsanationEligibility>>, TError = unknown>(
 subphaseId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof subsanationEligibility>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof subsanationEligibility>>,
          TError,
          Awaited<ReturnType<typeof subsanationEligibility>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSubsanationEligibility<TData = Awaited<ReturnType<typeof subsanationEligibility>>, TError = unknown>(
 subphaseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subsanationEligibility>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof subsanationEligibility>>,
          TError,
          Awaited<ReturnType<typeof subsanationEligibility>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSubsanationEligibility<TData = Awaited<ReturnType<typeof subsanationEligibility>>, TError = unknown>(
 subphaseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subsanationEligibility>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Verificar si la subfase permite subsanación
 */

export function useSubsanationEligibility<TData = Awaited<ReturnType<typeof subsanationEligibility>>, TError = unknown>(
 subphaseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subsanationEligibility>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSubsanationEligibilityQueryOptions(subphaseId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






