/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateLevel1NodeRequestDto,
  CreateNormativeIndicatorRequestDto,
  CreateNormativeNodeRequestDto,
  NormativeIndicatorDto,
  NormativeLevel1NodeDto,
  NormativeLevel2NodeDto,
  NormativeLevel3NodeDto,
  UpdateLevel1NodeRequestDto,
  UpdateNormativeIndicatorRequestDto,
  UpdateNormativeNodeRequestDto
} from '../../model';

import { customFetch } from '../../../lib/api/customFetch.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type updateLevel3Response200 = {
  data: NormativeLevel3NodeDto
  status: 200
}

export type updateLevel3ResponseSuccess = (updateLevel3Response200) & {
  headers: Headers;
};
;

export type updateLevel3Response = (updateLevel3ResponseSuccess)

export const getUpdateLevel3Url = (templateId: string,
    level3Id: string,) => {




  return `/api/v1/templates/${templateId}/level3-nodes/${level3Id}`
}

export const updateLevel3 = async (templateId: string,
    level3Id: string,
    updateNormativeNodeRequestDto: UpdateNormativeNodeRequestDto, options?: Parameters<typeof customFetch>[1]): Promise<updateLevel3Response> => {

  return customFetch<updateLevel3Response>(getUpdateLevel3Url(templateId,level3Id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateNormativeNodeRequestDto)
  }
);}





export const getUpdateLevel3MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLevel3>>, TError,{templateId: string;level3Id: string;data: UpdateNormativeNodeRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateLevel3>>, TError,{templateId: string;level3Id: string;data: UpdateNormativeNodeRequestDto}, TContext> => {

const mutationKey = ['updateLevel3'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateLevel3>>, {templateId: string;level3Id: string;data: UpdateNormativeNodeRequestDto}> = (props) => {
          const {templateId,level3Id,data} = props ?? {};

          return  updateLevel3(templateId,level3Id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateLevel3MutationResult = NonNullable<Awaited<ReturnType<typeof updateLevel3>>>
    export type UpdateLevel3MutationBody = UpdateNormativeNodeRequestDto
    export type UpdateLevel3MutationError = unknown

    export const useUpdateLevel3 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLevel3>>, TError,{templateId: string;level3Id: string;data: UpdateNormativeNodeRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateLevel3>>,
        TError,
        {templateId: string;level3Id: string;data: UpdateNormativeNodeRequestDto},
        TContext
      > => {
      return useMutation(getUpdateLevel3MutationOptions(options), queryClient);
    }
    export type deleteLevel3Response200 = {
  data: void
  status: 200
}

export type deleteLevel3ResponseSuccess = (deleteLevel3Response200) & {
  headers: Headers;
};
;

export type deleteLevel3Response = (deleteLevel3ResponseSuccess)

export const getDeleteLevel3Url = (templateId: string,
    level3Id: string,) => {




  return `/api/v1/templates/${templateId}/level3-nodes/${level3Id}`
}

export const deleteLevel3 = async (templateId: string,
    level3Id: string, options?: Parameters<typeof customFetch>[1]): Promise<deleteLevel3Response> => {

  return customFetch<deleteLevel3Response>(getDeleteLevel3Url(templateId,level3Id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteLevel3MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLevel3>>, TError,{templateId: string;level3Id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteLevel3>>, TError,{templateId: string;level3Id: string}, TContext> => {

const mutationKey = ['deleteLevel3'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteLevel3>>, {templateId: string;level3Id: string}> = (props) => {
          const {templateId,level3Id} = props ?? {};

          return  deleteLevel3(templateId,level3Id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteLevel3MutationResult = NonNullable<Awaited<ReturnType<typeof deleteLevel3>>>

    export type DeleteLevel3MutationError = unknown

    export const useDeleteLevel3 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLevel3>>, TError,{templateId: string;level3Id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteLevel3>>,
        TError,
        {templateId: string;level3Id: string},
        TContext
      > => {
      return useMutation(getDeleteLevel3MutationOptions(options), queryClient);
    }
    export type updateLevel2Response200 = {
  data: NormativeLevel2NodeDto
  status: 200
}

export type updateLevel2ResponseSuccess = (updateLevel2Response200) & {
  headers: Headers;
};
;

export type updateLevel2Response = (updateLevel2ResponseSuccess)

export const getUpdateLevel2Url = (templateId: string,
    level2Id: string,) => {




  return `/api/v1/templates/${templateId}/level2-nodes/${level2Id}`
}

export const updateLevel2 = async (templateId: string,
    level2Id: string,
    updateNormativeNodeRequestDto: UpdateNormativeNodeRequestDto, options?: Parameters<typeof customFetch>[1]): Promise<updateLevel2Response> => {

  return customFetch<updateLevel2Response>(getUpdateLevel2Url(templateId,level2Id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateNormativeNodeRequestDto)
  }
);}





export const getUpdateLevel2MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLevel2>>, TError,{templateId: string;level2Id: string;data: UpdateNormativeNodeRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateLevel2>>, TError,{templateId: string;level2Id: string;data: UpdateNormativeNodeRequestDto}, TContext> => {

const mutationKey = ['updateLevel2'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateLevel2>>, {templateId: string;level2Id: string;data: UpdateNormativeNodeRequestDto}> = (props) => {
          const {templateId,level2Id,data} = props ?? {};

          return  updateLevel2(templateId,level2Id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateLevel2MutationResult = NonNullable<Awaited<ReturnType<typeof updateLevel2>>>
    export type UpdateLevel2MutationBody = UpdateNormativeNodeRequestDto
    export type UpdateLevel2MutationError = unknown

    export const useUpdateLevel2 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLevel2>>, TError,{templateId: string;level2Id: string;data: UpdateNormativeNodeRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateLevel2>>,
        TError,
        {templateId: string;level2Id: string;data: UpdateNormativeNodeRequestDto},
        TContext
      > => {
      return useMutation(getUpdateLevel2MutationOptions(options), queryClient);
    }
    export type deleteLevel2Response200 = {
  data: void
  status: 200
}

export type deleteLevel2ResponseSuccess = (deleteLevel2Response200) & {
  headers: Headers;
};
;

export type deleteLevel2Response = (deleteLevel2ResponseSuccess)

export const getDeleteLevel2Url = (templateId: string,
    level2Id: string,) => {




  return `/api/v1/templates/${templateId}/level2-nodes/${level2Id}`
}

export const deleteLevel2 = async (templateId: string,
    level2Id: string, options?: Parameters<typeof customFetch>[1]): Promise<deleteLevel2Response> => {

  return customFetch<deleteLevel2Response>(getDeleteLevel2Url(templateId,level2Id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteLevel2MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLevel2>>, TError,{templateId: string;level2Id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteLevel2>>, TError,{templateId: string;level2Id: string}, TContext> => {

const mutationKey = ['deleteLevel2'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteLevel2>>, {templateId: string;level2Id: string}> = (props) => {
          const {templateId,level2Id} = props ?? {};

          return  deleteLevel2(templateId,level2Id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteLevel2MutationResult = NonNullable<Awaited<ReturnType<typeof deleteLevel2>>>

    export type DeleteLevel2MutationError = unknown

    export const useDeleteLevel2 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLevel2>>, TError,{templateId: string;level2Id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteLevel2>>,
        TError,
        {templateId: string;level2Id: string},
        TContext
      > => {
      return useMutation(getDeleteLevel2MutationOptions(options), queryClient);
    }
    export type updateLevel1Response200 = {
  data: NormativeLevel1NodeDto
  status: 200
}

export type updateLevel1ResponseSuccess = (updateLevel1Response200) & {
  headers: Headers;
};
;

export type updateLevel1Response = (updateLevel1ResponseSuccess)

export const getUpdateLevel1Url = (templateId: string,
    level1Id: string,) => {




  return `/api/v1/templates/${templateId}/level1-nodes/${level1Id}`
}

export const updateLevel1 = async (templateId: string,
    level1Id: string,
    updateLevel1NodeRequestDto: UpdateLevel1NodeRequestDto, options?: Parameters<typeof customFetch>[1]): Promise<updateLevel1Response> => {

  return customFetch<updateLevel1Response>(getUpdateLevel1Url(templateId,level1Id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateLevel1NodeRequestDto)
  }
);}





export const getUpdateLevel1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLevel1>>, TError,{templateId: string;level1Id: string;data: UpdateLevel1NodeRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateLevel1>>, TError,{templateId: string;level1Id: string;data: UpdateLevel1NodeRequestDto}, TContext> => {

const mutationKey = ['updateLevel1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateLevel1>>, {templateId: string;level1Id: string;data: UpdateLevel1NodeRequestDto}> = (props) => {
          const {templateId,level1Id,data} = props ?? {};

          return  updateLevel1(templateId,level1Id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateLevel1MutationResult = NonNullable<Awaited<ReturnType<typeof updateLevel1>>>
    export type UpdateLevel1MutationBody = UpdateLevel1NodeRequestDto
    export type UpdateLevel1MutationError = unknown

    export const useUpdateLevel1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLevel1>>, TError,{templateId: string;level1Id: string;data: UpdateLevel1NodeRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateLevel1>>,
        TError,
        {templateId: string;level1Id: string;data: UpdateLevel1NodeRequestDto},
        TContext
      > => {
      return useMutation(getUpdateLevel1MutationOptions(options), queryClient);
    }
    export type deleteLevel1Response200 = {
  data: void
  status: 200
}

export type deleteLevel1ResponseSuccess = (deleteLevel1Response200) & {
  headers: Headers;
};
;

export type deleteLevel1Response = (deleteLevel1ResponseSuccess)

export const getDeleteLevel1Url = (templateId: string,
    level1Id: string,) => {




  return `/api/v1/templates/${templateId}/level1-nodes/${level1Id}`
}

export const deleteLevel1 = async (templateId: string,
    level1Id: string, options?: Parameters<typeof customFetch>[1]): Promise<deleteLevel1Response> => {

  return customFetch<deleteLevel1Response>(getDeleteLevel1Url(templateId,level1Id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteLevel1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLevel1>>, TError,{templateId: string;level1Id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteLevel1>>, TError,{templateId: string;level1Id: string}, TContext> => {

const mutationKey = ['deleteLevel1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteLevel1>>, {templateId: string;level1Id: string}> = (props) => {
          const {templateId,level1Id} = props ?? {};

          return  deleteLevel1(templateId,level1Id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteLevel1MutationResult = NonNullable<Awaited<ReturnType<typeof deleteLevel1>>>

    export type DeleteLevel1MutationError = unknown

    export const useDeleteLevel1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLevel1>>, TError,{templateId: string;level1Id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteLevel1>>,
        TError,
        {templateId: string;level1Id: string},
        TContext
      > => {
      return useMutation(getDeleteLevel1MutationOptions(options), queryClient);
    }
    export type updateIndicatorResponse200 = {
  data: NormativeIndicatorDto
  status: 200
}

export type updateIndicatorResponseSuccess = (updateIndicatorResponse200) & {
  headers: Headers;
};
;

export type updateIndicatorResponse = (updateIndicatorResponseSuccess)

export const getUpdateIndicatorUrl = (indicatorId: string,) => {




  return `/api/v1/template-indicators/${indicatorId}`
}

export const updateIndicator = async (indicatorId: string,
    updateNormativeIndicatorRequestDto: UpdateNormativeIndicatorRequestDto, options?: Parameters<typeof customFetch>[1]): Promise<updateIndicatorResponse> => {

  return customFetch<updateIndicatorResponse>(getUpdateIndicatorUrl(indicatorId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateNormativeIndicatorRequestDto)
  }
);}





export const getUpdateIndicatorMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateIndicator>>, TError,{indicatorId: string;data: UpdateNormativeIndicatorRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateIndicator>>, TError,{indicatorId: string;data: UpdateNormativeIndicatorRequestDto}, TContext> => {

const mutationKey = ['updateIndicator'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateIndicator>>, {indicatorId: string;data: UpdateNormativeIndicatorRequestDto}> = (props) => {
          const {indicatorId,data} = props ?? {};

          return  updateIndicator(indicatorId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateIndicatorMutationResult = NonNullable<Awaited<ReturnType<typeof updateIndicator>>>
    export type UpdateIndicatorMutationBody = UpdateNormativeIndicatorRequestDto
    export type UpdateIndicatorMutationError = unknown

    export const useUpdateIndicator = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateIndicator>>, TError,{indicatorId: string;data: UpdateNormativeIndicatorRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateIndicator>>,
        TError,
        {indicatorId: string;data: UpdateNormativeIndicatorRequestDto},
        TContext
      > => {
      return useMutation(getUpdateIndicatorMutationOptions(options), queryClient);
    }
    export type deleteIndicatorResponse200 = {
  data: void
  status: 200
}

export type deleteIndicatorResponseSuccess = (deleteIndicatorResponse200) & {
  headers: Headers;
};
;

export type deleteIndicatorResponse = (deleteIndicatorResponseSuccess)

export const getDeleteIndicatorUrl = (indicatorId: string,) => {




  return `/api/v1/template-indicators/${indicatorId}`
}

export const deleteIndicator = async (indicatorId: string, options?: Parameters<typeof customFetch>[1]): Promise<deleteIndicatorResponse> => {

  return customFetch<deleteIndicatorResponse>(getDeleteIndicatorUrl(indicatorId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteIndicatorMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteIndicator>>, TError,{indicatorId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteIndicator>>, TError,{indicatorId: string}, TContext> => {

const mutationKey = ['deleteIndicator'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteIndicator>>, {indicatorId: string}> = (props) => {
          const {indicatorId} = props ?? {};

          return  deleteIndicator(indicatorId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteIndicatorMutationResult = NonNullable<Awaited<ReturnType<typeof deleteIndicator>>>

    export type DeleteIndicatorMutationError = unknown

    export const useDeleteIndicator = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteIndicator>>, TError,{indicatorId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteIndicator>>,
        TError,
        {indicatorId: string},
        TContext
      > => {
      return useMutation(getDeleteIndicatorMutationOptions(options), queryClient);
    }
    export type addIndicatorResponse200 = {
  data: NormativeIndicatorDto
  status: 200
}

export type addIndicatorResponseSuccess = (addIndicatorResponse200) & {
  headers: Headers;
};
;

export type addIndicatorResponse = (addIndicatorResponseSuccess)

export const getAddIndicatorUrl = (templateId: string,
    level3Id: string,) => {




  return `/api/v1/templates/${templateId}/level3-nodes/${level3Id}/indicators`
}

export const addIndicator = async (templateId: string,
    level3Id: string,
    createNormativeIndicatorRequestDto: CreateNormativeIndicatorRequestDto, options?: Parameters<typeof customFetch>[1]): Promise<addIndicatorResponse> => {

  return customFetch<addIndicatorResponse>(getAddIndicatorUrl(templateId,level3Id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createNormativeIndicatorRequestDto)
  }
);}





export const getAddIndicatorMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addIndicator>>, TError,{templateId: string;level3Id: string;data: CreateNormativeIndicatorRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof addIndicator>>, TError,{templateId: string;level3Id: string;data: CreateNormativeIndicatorRequestDto}, TContext> => {

const mutationKey = ['addIndicator'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addIndicator>>, {templateId: string;level3Id: string;data: CreateNormativeIndicatorRequestDto}> = (props) => {
          const {templateId,level3Id,data} = props ?? {};

          return  addIndicator(templateId,level3Id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddIndicatorMutationResult = NonNullable<Awaited<ReturnType<typeof addIndicator>>>
    export type AddIndicatorMutationBody = CreateNormativeIndicatorRequestDto
    export type AddIndicatorMutationError = unknown

    export const useAddIndicator = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addIndicator>>, TError,{templateId: string;level3Id: string;data: CreateNormativeIndicatorRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addIndicator>>,
        TError,
        {templateId: string;level3Id: string;data: CreateNormativeIndicatorRequestDto},
        TContext
      > => {
      return useMutation(getAddIndicatorMutationOptions(options), queryClient);
    }
    export type addLevel3Response200 = {
  data: NormativeLevel3NodeDto
  status: 200
}

export type addLevel3ResponseSuccess = (addLevel3Response200) & {
  headers: Headers;
};
;

export type addLevel3Response = (addLevel3ResponseSuccess)

export const getAddLevel3Url = (templateId: string,
    level2Id: string,) => {




  return `/api/v1/templates/${templateId}/level2-nodes/${level2Id}/level3-nodes`
}

export const addLevel3 = async (templateId: string,
    level2Id: string,
    createNormativeNodeRequestDto: CreateNormativeNodeRequestDto, options?: Parameters<typeof customFetch>[1]): Promise<addLevel3Response> => {

  return customFetch<addLevel3Response>(getAddLevel3Url(templateId,level2Id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createNormativeNodeRequestDto)
  }
);}





export const getAddLevel3MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addLevel3>>, TError,{templateId: string;level2Id: string;data: CreateNormativeNodeRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof addLevel3>>, TError,{templateId: string;level2Id: string;data: CreateNormativeNodeRequestDto}, TContext> => {

const mutationKey = ['addLevel3'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addLevel3>>, {templateId: string;level2Id: string;data: CreateNormativeNodeRequestDto}> = (props) => {
          const {templateId,level2Id,data} = props ?? {};

          return  addLevel3(templateId,level2Id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddLevel3MutationResult = NonNullable<Awaited<ReturnType<typeof addLevel3>>>
    export type AddLevel3MutationBody = CreateNormativeNodeRequestDto
    export type AddLevel3MutationError = unknown

    export const useAddLevel3 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addLevel3>>, TError,{templateId: string;level2Id: string;data: CreateNormativeNodeRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addLevel3>>,
        TError,
        {templateId: string;level2Id: string;data: CreateNormativeNodeRequestDto},
        TContext
      > => {
      return useMutation(getAddLevel3MutationOptions(options), queryClient);
    }
    export type listLevel1NodesResponse200 = {
  data: NormativeLevel1NodeDto[]
  status: 200
}

export type listLevel1NodesResponseSuccess = (listLevel1NodesResponse200) & {
  headers: Headers;
};
;

export type listLevel1NodesResponse = (listLevel1NodesResponseSuccess)

export const getListLevel1NodesUrl = (templateId: string,) => {




  return `/api/v1/templates/${templateId}/level1-nodes`
}

/**
 * @summary Listar nodos Nivel 1 de la plantilla
 */
export const listLevel1Nodes = async (templateId: string, options?: Parameters<typeof customFetch>[1]): Promise<listLevel1NodesResponse> => {

  return customFetch<listLevel1NodesResponse>(getListLevel1NodesUrl(templateId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListLevel1NodesQueryKey = (templateId: string,) => {
    return [
    `/api/v1/templates/${templateId}/level1-nodes`
    ] as const;
    }


export const getListLevel1NodesQueryOptions = <TData = Awaited<ReturnType<typeof listLevel1Nodes>>, TError = unknown>(templateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLevel1Nodes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListLevel1NodesQueryKey(templateId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listLevel1Nodes>>> = ({ signal }) => listLevel1Nodes(templateId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: templateId !== null && templateId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listLevel1Nodes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListLevel1NodesQueryResult = NonNullable<Awaited<ReturnType<typeof listLevel1Nodes>>>
export type ListLevel1NodesQueryError = unknown


export function useListLevel1Nodes<TData = Awaited<ReturnType<typeof listLevel1Nodes>>, TError = unknown>(
 templateId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLevel1Nodes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLevel1Nodes>>,
          TError,
          Awaited<ReturnType<typeof listLevel1Nodes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListLevel1Nodes<TData = Awaited<ReturnType<typeof listLevel1Nodes>>, TError = unknown>(
 templateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLevel1Nodes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLevel1Nodes>>,
          TError,
          Awaited<ReturnType<typeof listLevel1Nodes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListLevel1Nodes<TData = Awaited<ReturnType<typeof listLevel1Nodes>>, TError = unknown>(
 templateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLevel1Nodes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar nodos Nivel 1 de la plantilla
 */

export function useListLevel1Nodes<TData = Awaited<ReturnType<typeof listLevel1Nodes>>, TError = unknown>(
 templateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLevel1Nodes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListLevel1NodesQueryOptions(templateId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type addLevel1Response200 = {
  data: NormativeLevel1NodeDto
  status: 200
}

export type addLevel1ResponseSuccess = (addLevel1Response200) & {
  headers: Headers;
};
;

export type addLevel1Response = (addLevel1ResponseSuccess)

export const getAddLevel1Url = (templateId: string,) => {




  return `/api/v1/templates/${templateId}/level1-nodes`
}

/**
 * @summary Crear Nivel 1 en plantilla DRAFT
 */
export const addLevel1 = async (templateId: string,
    createLevel1NodeRequestDto: CreateLevel1NodeRequestDto, options?: Parameters<typeof customFetch>[1]): Promise<addLevel1Response> => {

  return customFetch<addLevel1Response>(getAddLevel1Url(templateId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createLevel1NodeRequestDto)
  }
);}





export const getAddLevel1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addLevel1>>, TError,{templateId: string;data: CreateLevel1NodeRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof addLevel1>>, TError,{templateId: string;data: CreateLevel1NodeRequestDto}, TContext> => {

const mutationKey = ['addLevel1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addLevel1>>, {templateId: string;data: CreateLevel1NodeRequestDto}> = (props) => {
          const {templateId,data} = props ?? {};

          return  addLevel1(templateId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddLevel1MutationResult = NonNullable<Awaited<ReturnType<typeof addLevel1>>>
    export type AddLevel1MutationBody = CreateLevel1NodeRequestDto
    export type AddLevel1MutationError = unknown

    /**
 * @summary Crear Nivel 1 en plantilla DRAFT
 */
export const useAddLevel1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addLevel1>>, TError,{templateId: string;data: CreateLevel1NodeRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addLevel1>>,
        TError,
        {templateId: string;data: CreateLevel1NodeRequestDto},
        TContext
      > => {
      return useMutation(getAddLevel1MutationOptions(options), queryClient);
    }
    export type addLevel2Response200 = {
  data: NormativeLevel2NodeDto
  status: 200
}

export type addLevel2ResponseSuccess = (addLevel2Response200) & {
  headers: Headers;
};
;

export type addLevel2Response = (addLevel2ResponseSuccess)

export const getAddLevel2Url = (templateId: string,
    level1Id: string,) => {




  return `/api/v1/templates/${templateId}/level1-nodes/${level1Id}/level2-nodes`
}

export const addLevel2 = async (templateId: string,
    level1Id: string,
    createNormativeNodeRequestDto: CreateNormativeNodeRequestDto, options?: Parameters<typeof customFetch>[1]): Promise<addLevel2Response> => {

  return customFetch<addLevel2Response>(getAddLevel2Url(templateId,level1Id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createNormativeNodeRequestDto)
  }
);}





export const getAddLevel2MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addLevel2>>, TError,{templateId: string;level1Id: string;data: CreateNormativeNodeRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof addLevel2>>, TError,{templateId: string;level1Id: string;data: CreateNormativeNodeRequestDto}, TContext> => {

const mutationKey = ['addLevel2'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addLevel2>>, {templateId: string;level1Id: string;data: CreateNormativeNodeRequestDto}> = (props) => {
          const {templateId,level1Id,data} = props ?? {};

          return  addLevel2(templateId,level1Id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddLevel2MutationResult = NonNullable<Awaited<ReturnType<typeof addLevel2>>>
    export type AddLevel2MutationBody = CreateNormativeNodeRequestDto
    export type AddLevel2MutationError = unknown

    export const useAddLevel2 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addLevel2>>, TError,{templateId: string;level1Id: string;data: CreateNormativeNodeRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addLevel2>>,
        TError,
        {templateId: string;level1Id: string;data: CreateNormativeNodeRequestDto},
        TContext
      > => {
      return useMutation(getAddLevel2MutationOptions(options), queryClient);
    }
